Repository apify/crawlee-python, pull requests merged in 2024-11, with the labels that each got.

#640 docs: smaller documentation fixes (GitHub links, type parsing etc.)
  .gitignore
  website/build_api_reference.sh
  website/package.json
  website/parse_types.py
  website/pydoc-markdown/generate_ast.py
  website/transformDocs.js
  website/yarn.lock
Labels: t-tooling, adhoc

#639 chore!: Remove Request.query_params field
  docs/examples/fill_and_submit_web_form.mdx
  src/crawlee/_request.py
  src/crawlee/_types.py
  src/crawlee/http_clients/_base.py
  src/crawlee/http_clients/_httpx.py
  src/crawlee/http_clients/curl_impersonate.py
  tests/unit/http_crawler/test_http_crawler.py
Labels: t-tooling, tested

#641 docs: fix docstring format of typed dicts
  .pre-commit-config.yaml
  src/crawlee/storages/_dataset.py
Labels: t-tooling, adhoc

#642 docs: add upgrading to v0.4 section
  CHANGELOG.md
  docs/upgrading/upgrading_to_v0x.md
Labels: documentation, t-tooling, adhoc

#652 docs: update guides dir structure
  docs/guides/code/http_clients/curl_impersonate.py
  docs/guides/code/http_clients/httpx.py
  docs/guides/code/proxy_management/inspecting_bs.py
  docs/guides/code/proxy_management/inspecting_pw.py
  docs/guides/code/proxy_management/integration_bs.py
  docs/guides/code/proxy_management/integration_pw.py
  docs/guides/code/proxy_management/quick_start.py
  docs/guides/code/proxy_management/session_bs.py
  docs/guides/code/proxy_management/session_pw.py
  docs/guides/code/proxy_management/tiers_bs.py
  docs/guides/code/proxy_management/tiers_pw.py
  docs/guides/code/request_storage/do_not_purge.py
  docs/guides/code/request_storage/helper_add_requests.py
  docs/guides/code/request_storage/helper_enqueue_links.py
  docs/guides/code/request_storage/purge_explicitly.py
  docs/guides/code/request_storage/rl_basic.py
  docs/guides/code/request_storage/rl_with_crawler.py
  docs/guides/code/request_storage/rq_basic.py
  docs/guides/code/request_storage/rq_with_crawler.py
  docs/guides/code/request_storage/rq_with_crawler_explicit.py
  docs/guides/code/result_storage/dataset_basic.py
  docs/guides/code/result_storage/dataset_with_crawler.py
  docs/guides/code/result_storage/dataset_with_crawler_explicit.py
  docs/guides/code/result_storage/kvs_basic.py
  docs/guides/code/result_storage/kvs_with_crawler.py
  docs/guides/code/result_storage/kvs_with_crawler_explicit.py
  docs/guides/code/scaling_crawlers/max_tasks_per_minute.py
  docs/guides/code/scaling_crawlers/min_and_max_concurrency.py
  docs/guides/http_clients.mdx
  docs/guides/proxy_management.mdx
  docs/guides/request_storage.mdx
  docs/guides/result_storage.mdx
  docs/guides/scaling_crawlers.mdx
Labels: documentation, t-tooling, adhoc

#656 chore: Remove remnants of scripts folder
  pyproject.toml
Labels: t-tooling, adhoc

#657 docs: update example file names to fix type checking
  docs/guides/code/http_clients/curl_impersonate_example.py
  docs/guides/code/http_clients/httpx_example.py
  docs/guides/code/proxy_management/inspecting_bs_example.py
  docs/guides/code/proxy_management/inspecting_pw_example.py
  docs/guides/code/proxy_management/integration_bs_example.py
  docs/guides/code/proxy_management/integration_pw_example.py
  docs/guides/code/proxy_management/quick_start_example.py
  docs/guides/code/proxy_management/session_bs_example.py
  docs/guides/code/proxy_management/session_pw_example.py
  docs/guides/code/proxy_management/tiers_bs_example.py
  docs/guides/code/proxy_management/tiers_pw_example.py
  docs/guides/code/request_storage/do_not_purge_example.py
  docs/guides/code/request_storage/helper_add_requests_example.py
  docs/guides/code/request_storage/helper_enqueue_links_example.py
  docs/guides/code/request_storage/purge_explicitly_example.py
  docs/guides/code/request_storage/rl_basic_example.py
  docs/guides/code/request_storage/rl_with_crawler_example.py
  docs/guides/code/request_storage/rq_basic_example.py
  docs/guides/code/request_storage/rq_with_crawler_example.py
  docs/guides/code/request_storage/rq_with_crawler_explicit_example.py
  docs/guides/code/result_storage/dataset_basic_example.py
  docs/guides/code/result_storage/dataset_with_crawler_example.py
  docs/guides/code/result_storage/dataset_with_crawler_explicit_example.py
  docs/guides/code/result_storage/kvs_basic_example.py
  docs/guides/code/result_storage/kvs_with_crawler_example.py
  docs/guides/code/result_storage/kvs_with_crawler_explicit_example.py
  docs/guides/code/scaling_crawlers/max_tasks_per_minute_example.py
  docs/guides/code/scaling_crawlers/min_and_max_concurrency_example.py
  docs/guides/http_clients.mdx
  docs/guides/proxy_management.mdx
  docs/guides/request_storage.mdx
  docs/guides/result_storage.mdx
  docs/guides/scaling_crawlers.mdx
Labels: documentation, t-tooling, adhoc

#661 fix: Fix total_size usage in memory size monitoring
  src/crawlee/_autoscaling/snapshotter.py
  src/crawlee/_autoscaling/types.py
  src/crawlee/_utils/system.py
  src/crawlee/events/_types.py
  tests/unit/_autoscaling/test_snapshotter.py
  tests/unit/_autoscaling/test_system_status.py
Labels: t-tooling, adhoc, tested

#665 chore: update identifiers & API docs in `_types` module
  src/crawlee/_types.py
  src/crawlee/beautifulsoup_crawler/_beautifulsoup_crawler.py
  src/crawlee/parsel_crawler/_parsel_crawler.py
  src/crawlee/playwright_crawler/_playwright_crawler.py
  tests/unit/basic_crawler/test_basic_crawler.py
Labels: documentation, t-tooling, adhoc, tested

#664 fix: Add HttpHeaders to module exports
  src/crawlee/__init__.py
Labels: t-tooling

#667 chore: make HTTP headers more user friendly
  src/crawlee/_request.py
  src/crawlee/_types.py
  src/crawlee/basic_crawler/_basic_crawler.py
  src/crawlee/http_clients/_base.py
  src/crawlee/http_clients/_httpx.py
  src/crawlee/http_clients/curl_impersonate.py
Labels: t-tooling, adhoc

#660 chore: update dev configs
  .gitignore
  .pre-commit-config.yaml
  CONTRIBUTING.md
  Makefile
Labels: t-tooling, adhoc

#666 fix: Fix unhandled ValueError in request handler result processing
  src/crawlee/_types.py
  src/crawlee/storages/_dataset.py
  tests/unit/basic_crawler/test_basic_crawler.py
Labels: t-tooling, adhoc, tested

#674 feat: Add BeautifulSoupParser type alias
  src/crawlee/beautifulsoup_crawler/__init__.py
  src/crawlee/beautifulsoup_crawler/_beautifulsoup_crawler.py
Labels: t-tooling, adhoc

#671 docs: improve docs of the `Configuration` class
  src/crawlee/configuration.py
Labels: t-tooling

#655 docs: Add `@docs_group` decorator
  src/crawlee/_autoscaling/autoscaled_pool.py
  src/crawlee/_autoscaling/snapshotter.py
  src/crawlee/_autoscaling/system_status.py
  src/crawlee/_request.py
  src/crawlee/_types.py
  src/crawlee/_utils/docs.py
  src/crawlee/base_storage_client/_base_dataset_client.py
  src/crawlee/base_storage_client/_base_dataset_collection_client.py
  src/crawlee/base_storage_client/_base_key_value_store_client.py
  src/crawlee/base_storage_client/_base_key_value_store_collection_client.py
  src/crawlee/base_storage_client/_base_request_queue_client.py
  src/crawlee/base_storage_client/_base_request_queue_collection_client.py
  src/crawlee/base_storage_client/_base_storage_client.py
  src/crawlee/base_storage_client/_models.py
  src/crawlee/basic_crawler/_basic_crawler.py
  src/crawlee/basic_crawler/_context_pipeline.py
  src/crawlee/beautifulsoup_crawler/_beautifulsoup_crawler.py
  src/crawlee/beautifulsoup_crawler/_beautifulsoup_crawling_context.py
  src/crawlee/browsers/_browser_pool.py
  src/crawlee/browsers/_playwright_browser_controller.py
  src/crawlee/browsers/_playwright_browser_plugin.py
  src/crawlee/configuration.py
  src/crawlee/errors.py
  src/crawlee/events/_event_manager.py
  src/crawlee/events/_local_event_manager.py
  src/crawlee/fingerprint_suite/_header_generator.py
  src/crawlee/http_clients/_base.py
  src/crawlee/http_clients/_httpx.py
  src/crawlee/http_clients/curl_impersonate.py
  src/crawlee/http_crawler/_http_crawler.py
  src/crawlee/http_crawler/_http_crawling_context.py
  src/crawlee/memory_storage_client/_memory_storage_client.py
  src/crawlee/parsel_crawler/_parsel_crawler.py
  src/crawlee/parsel_crawler/_parsel_crawling_context.py
  src/crawlee/playwright_crawler/_playwright_crawler.py
  src/crawlee/playwright_crawler/_playwright_crawling_context.py
  src/crawlee/playwright_crawler/_playwright_pre_navigation_context.py
  src/crawlee/proxy_configuration.py
  src/crawlee/router.py
  src/crawlee/service_container.py
  src/crawlee/sessions/_session.py
  src/crawlee/sessions/_session_pool.py
  src/crawlee/statistics/_models.py
  src/crawlee/statistics/_statistics.py
  src/crawlee/storages/_dataset.py
  src/crawlee/storages/_key_value_store.py
  src/crawlee/storages/_request_list.py
  src/crawlee/storages/_request_provider.py
  src/crawlee/storages/_request_queue.py
  website/transformDocs.js
Labels: t-tooling

#681 chore: add poetry lock file
  .gitignore
  poetry.lock
Labels: t-tooling

#686 chore(deps): Update apify SDK version
  poetry.lock
Labels: t-tooling, adhoc

#685 fix: respect custom HTTP headers in `PlaywrightCrawler`
  src/crawlee/playwright_crawler/_playwright_crawler.py
  tests/unit/playwright_crawler/test_playwright_crawler.py
Labels: bug, t-tooling

#683 fix: Fix serialization payload in Request. Fix Docs for Post Request
  docs/examples/code/fill_and_submit_web_form_crawler.py
  docs/examples/code/fill_and_submit_web_form_request.py
  src/crawlee/_request.py
  tests/unit/_memory_storage_client/test_request_queue_client.py
Labels: bug, t-tooling

#688 chore: add tests for processing request payload
  src/crawlee/_request.py
  tests/unit/_memory_storage_client/test_request_queue_client.py
  tests/unit/http_crawler/test_http_crawler.py
Labels: t-tooling

#697 fix: Accept string payload in the Request constructor
  src/crawlee/_request.py
Labels: bug, t-tooling, adhoc

#692 fix: Fix snapshots handling
  poetry.lock
  pyproject.toml
  src/crawlee/_autoscaling/snapshotter.py
  src/crawlee/_autoscaling/system_status.py
  src/crawlee/_utils/math.py
  tests/unit/_autoscaling/test_snapshotter.py
  tests/unit/_autoscaling/test_system_status.py
  tests/unit/_utils/test_math.py
Labels: bug, t-tooling, tested

#167 ci: Use a custom httpbin instance in tests
  .github/workflows/run_code_checks.yaml
  src/crawlee/beautifulsoup_crawler/_beautifulsoup_crawler.py
  src/crawlee/http_crawler/_http_crawler.py
  src/crawlee/parsel_crawler/_parsel_crawler.py
  tests/unit/basic_crawler/test_basic_crawler.py
  tests/unit/browsers/test_browser_pool.py
  tests/unit/browsers/test_playwright_browser_controller.py
  tests/unit/browsers/test_playwright_browser_plugin.py
  tests/unit/conftest.py
  tests/unit/http_clients/test_curl_impersonate.py
  tests/unit/http_clients/test_httpx.py
  tests/unit/http_crawler/test_http_crawler.py
  tests/unit/playwright_crawler/test_playwright_crawler.py
Labels: t-tooling, tested

#711 chore: Use runtime-evaluated-base-classes for ruff
  pyproject.toml
  src/crawlee/_request.py
  src/crawlee/_utils/system.py
  src/crawlee/base_storage_client/_models.py
  src/crawlee/beautifulsoup_crawler/_beautifulsoup_crawler.py
  src/crawlee/configuration.py
  src/crawlee/events/_event_manager.py
  src/crawlee/events/_local_event_manager.py
  src/crawlee/events/_types.py
  src/crawlee/http_crawler/_http_crawler.py
  src/crawlee/parsel_crawler/_parsel_crawler.py
  src/crawlee/playwright_crawler/_playwright_crawler.py
  src/crawlee/sessions/_models.py
  src/crawlee/statistics/_models.py
Labels: t-tooling, adhoc, debt

#713 docs: update `@apify/docusaurus-plugin-typedoc-api`
  Makefile
  website/build_api_reference.sh
  website/docusaurus.config.js
  website/package.json
  website/parse_types.py
  website/pydoc-markdown.yml
  website/transformDocs.js
  website/yarn.lock
Labels: documentation, t-tooling, adhoc

#716 fix: Pydantic 2.10.0 issues
  poetry.lock
  pyproject.toml
Labels: t-tooling, adhoc

#718 ci: update Renove schedule
  renovate.json
Labels: t-tooling, adhoc

#730 feat: Expose browser_options and page_options to PlaywrightCrawler
  src/crawlee/browsers/_browser_pool.py
  src/crawlee/browsers/_playwright_browser_plugin.py
  src/crawlee/playwright_crawler/_playwright_crawler.py
Labels: t-tooling

#738 chore: update Ruff to 0.8
  poetry.lock
  pyproject.toml
  src/crawlee/_autoscaling/autoscaled_pool.py
  src/crawlee/_utils/lru_cache.py
  src/crawlee/_utils/measure_time.py
  src/crawlee/base_storage_client/_base_dataset_client.py
  src/crawlee/base_storage_client/_base_key_value_store_client.py
  src/crawlee/basic_crawler/__init__.py
  src/crawlee/basic_crawler/_basic_crawler.py
  src/crawlee/basic_crawler/_context_pipeline.py
  src/crawlee/beautifulsoup_crawler/_beautifulsoup_crawler.py
  src/crawlee/errors.py
  src/crawlee/http_crawler/_http_crawler.py
  src/crawlee/memory_storage_client/_dataset_client.py
  src/crawlee/memory_storage_client/_key_value_store_client.py
  src/crawlee/parsel_crawler/_parsel_crawler.py
  src/crawlee/playwright_crawler/_playwright_crawler.py
  src/crawlee/playwright_crawler/_playwright_crawling_context.py
  src/crawlee/proxy_configuration.py
  src/crawlee/router.py
  src/crawlee/service_container.py
  src/crawlee/storages/_dataset.py
  src/crawlee/storages/_key_value_store.py
  tests/unit/_autoscaling/test_autoscaled_pool.py
  tests/unit/_autoscaling/test_system_status.py
  tests/unit/basic_crawler/test_context_pipeline.py
  tests/unit/beautifulsoup_crawler/test_beautifulsoup_crawler.py
  tests/unit/browsers/test_playwright_browser_controller.py
  tests/unit/browsers/test_playwright_browser_plugin.py
  tests/unit/events/test_event_manager.py
  tests/unit/http_crawler/test_http_crawler.py
  tests/unit/parsel_crawler/test_parsel_crawler.py
  tests/unit/sessions/test_session_pool.py
  tests/unit/storages/test_dataset.py
  tests/unit/storages/test_key_value_store.py
Labels: t-tooling, adhoc, tested

#714 fix: Fix init of context managers and context handling in `BasicCrawler`
  src/crawlee/_autoscaling/snapshotter.py
  src/crawlee/_utils/context.py
  src/crawlee/basic_crawler/_basic_crawler.py
  src/crawlee/browsers/_base_browser_plugin.py
  src/crawlee/browsers/_browser_pool.py
  src/crawlee/browsers/_playwright_browser_plugin.py
  src/crawlee/events/_event_manager.py
  src/crawlee/playwright_crawler/_utils.py
  src/crawlee/sessions/_session_pool.py
  src/crawlee/statistics/_statistics.py
  src/crawlee/storages/_request_queue.py
  tests/unit/_autoscaling/test_autoscaled_pool.py
  tests/unit/_autoscaling/test_snapshotter.py
  tests/unit/browsers/test_browser_pool.py
  tests/unit/browsers/test_playwright_browser_plugin.py
  tests/unit/events/test_event_manager.py
  tests/unit/http_crawler/test_http_crawler.py
  tests/unit/sessions/test_session_pool.py
Labels: bug, t-tooling, adhoc, tested

#739 ci: Pass secrets to docs build in pre-release
  .github/workflows/pre_release.yaml
Labels: t-tooling, adhoc

#749 chore: Remove custom parsing of `Session.max_age`
  poetry.lock
  pyproject.toml
  src/crawlee/sessions/_models.py
Labels: t-tooling

#752 docs: Move code snippets to separate files
  docs/deployment/apify_platform.mdx
  docs/deployment/code/apify/crawler_as_actor_example.py
  docs/deployment/code/apify/get_public_url.py
  docs/deployment/code/apify/log_with_config_example.py
  docs/deployment/code/apify/proxy_advanced_example.py
  docs/deployment/code/apify/proxy_example.py
  docs/deployment/code/apify_platform_get_public_url.py
  docs/deployment/code/apify_platform_main.py
  docs/introduction/03_adding_more_urls.mdx
  docs/introduction/code/03_enqueue_strategy.py
  docs/introduction/code/03_globs.py
  docs/quick-start/code/beautifulsoup_crawler_example.py
  docs/quick-start/code/parsel_crawler_example.py
  docs/quick-start/code/playwright_crawler_example.py
  docs/quick-start/code/playwright_crawler_headful_example.py
  docs/quick-start/index.mdx
Labels: documentation, t-tooling, adhoc

#754 chore: skip the curl crawl proxy flaky test
  tests/unit/http_clients/test_curl_impersonate.py
Labels: t-tooling, adhoc, tested

#762 ci: Fix dependencies in release workflow
  .github/workflows/release.yaml
Labels: t-tooling, adhoc

#763 chore: Remove unused ID arg from `BaseRequestData.from_url`
  src/crawlee/_request.py
Labels: t-tooling, adhoc
