Repository apify/crawlee-python, pull requests merged in 2024-08, with the labels that each got.

#378 docs: add webinar to readme
  README.md
Labels: t-tooling

#387 feat: add new curl impersonate HTTP client
  pyproject.toml
  src/crawlee/_utils/urls.py
  src/crawlee/basic_crawler/__init__.py
  src/crawlee/basic_crawler/basic_crawler.py
  src/crawlee/basic_crawler/context_pipeline.py
  src/crawlee/basic_crawler/router.py
  src/crawlee/basic_crawler/types.py
  src/crawlee/beautifulsoup_crawler/beautifulsoup_crawler.py
  src/crawlee/beautifulsoup_crawler/types.py
  src/crawlee/errors.py
  src/crawlee/http_clients/__init__.py
  src/crawlee/http_clients/base.py
  src/crawlee/http_clients/base_http_client.py
  src/crawlee/http_clients/curl_impersonate.py
  src/crawlee/http_clients/httpx.py
  src/crawlee/http_clients/httpx_client.py
  src/crawlee/http_crawler/http_crawler.py
  src/crawlee/http_crawler/types.py
  src/crawlee/models.py
  src/crawlee/playwright_crawler/playwright_crawler.py
  src/crawlee/playwright_crawler/types.py
  src/crawlee/types.py
  tests/unit/_utils/test_globs.py
  tests/unit/_utils/test_urls.py
  tests/unit/basic_crawler/test_basic_crawler.py
  tests/unit/basic_crawler/test_context_pipeline.py
  tests/unit/basic_crawler/test_router.py
  tests/unit/cli/test_create.py
  tests/unit/conftest.py
  tests/unit/http_clients/test_curl_impersonate.py
  tests/unit/http_clients/test_httpx.py
  tests/unit/httpx_client/test_httpx_client.py
  tests/unit/proxy_configuration/test_tiers.py
  tests/unit/statistics/test_periodic_logging.py
  tests/unit/statistics/test_persistence.py
  tests/unit/test_configuration.py
Labels: t-tooling, tested

#393 feat(playwright): `infinite_scroll` helper
  cliff.toml
  src/crawlee/playwright_crawler/playwright_crawler.py
  src/crawlee/playwright_crawler/types.py
  src/crawlee/playwright_crawler/utils.py
Labels: t-tooling, adhoc

#395 chore: Bump version
  pyproject.toml
Labels: t-tooling, adhoc

#396 fix: do not import curl impersonate in http clients init
  README.md
  docs/introduction/01-setting-up.mdx
  docs/quick-start/index.mdx
  pyproject.toml
  src/crawlee/http_clients/__init__.py
  src/crawlee/http_clients/curl_impersonate.py
  tests/unit/http_clients/test_curl_impersonate.py
Labels: bug, t-tooling, adhoc, tested

#397 chore: bump version to 0.2.1
  pyproject.toml
Labels: t-tooling, adhoc

#405 chore: bump version to 0.2.2
  pyproject.toml
Labels: t-tooling, adhoc

#406 docs: add guide for HTTP clients
  docs/guides/http_clients.mdx
  docs/guides/http_clients_examples/beautifulsoup_crawler_with_curl_impersonate.py
  docs/guides/http_clients_examples/beautifulsoup_crawler_with_httpx.py
  website/sidebars.js
Labels: t-tooling

#385 ci: Release process updates
  .github/workflows/_check_version_conflict.yaml
  .github/workflows/_publish_to_pypi.yaml
  .github/workflows/run_code_checks.yaml
  .github/workflows/run_release.yaml
  .pre-commit-config.yaml
  CHANGELOG.md
  CONTRIBUTING.md
  Makefile
  cliff.toml
  scripts/check_version_conflict.py
  scripts/fetch_pr_issues.sh
  scripts/preprocess_commit_message.py
  scripts/print_current_package_version.py
  scripts/update_version_for_prerelease.py
  scripts/utils.py
Labels: t-tooling

#322 fix: Remove indentation from statistics logging and print the data in tables
  src/crawlee/basic_crawler/basic_crawler.py
  src/crawlee/log_config.py
  src/crawlee/statistics/models.py
  src/crawlee/statistics/statistics.py
Labels: t-tooling

#407 ci: Add missing github token
  .github/workflows/run_release.yaml
Labels: t-tooling, adhoc

#348 feat: Implement ParselCrawler that adds support for Parsel
  docs/examples/parsel-crawler.mdx
  docs/introduction/01-setting-up.mdx
  docs/introduction/02-first-crawler.mdx
  pyproject.toml
  src/crawlee/parsel_crawler/__init__.py
  src/crawlee/parsel_crawler/parsel_crawler.py
  src/crawlee/parsel_crawler/types.py
  tests/unit/parsel_crawler/test_parsel_crawler.py
Labels: t-tooling

#409 chore: remove accidentaly committed file
  .gitignore
  pullRequestIssues.json
Labels: t-tooling, adhoc

#408 fix: Remove redundant log, fix format
  src/crawlee/basic_crawler/basic_crawler.py
  tests/unit/basic_crawler/test_basic_crawler.py
Labels: t-tooling, adhoc, tested

#411 fix: Dequeue items from RequestQueue in the correct order
  src/crawlee/storages/base_storage.py
  src/crawlee/storages/request_queue.py
  tests/unit/conftest.py
  tests/unit/memory_storage_client/test_memory_storage_e2e.py
Labels: t-tooling, adhoc, tested

#425 refactor: Remove dependency on aiofiles and aioshutil
  pyproject.toml
  src/crawlee/_utils/file.py
  src/crawlee/memory_storage_client/_creation_management.py
  src/crawlee/memory_storage_client/dataset_client.py
  src/crawlee/memory_storage_client/key_value_store_client.py
  src/crawlee/memory_storage_client/memory_storage_client.py
  src/crawlee/memory_storage_client/request_queue_client.py
  tests/unit/_utils/test_file.py
  tests/unit/memory_storage_client/test_creation_management.py
Labels: t-tooling, tested

#440 chore: update ruff to 0.6
  pyproject.toml
  tests/unit/_utils/test_lru_cache.py
  tests/unit/_utils/test_recurring_task.py
  tests/unit/autoscaling/test_autoscaled_pool.py
  tests/unit/autoscaling/test_snapshotter.py
  tests/unit/autoscaling/test_system_status.py
  tests/unit/beautifulsoup_crawler/test_beautifulsoup_crawler.py
  tests/unit/browsers/test_playwright_browser_controller.py
  tests/unit/browsers/test_playwright_browser_plugin.py
  tests/unit/cli/test_create.py
  tests/unit/conftest.py
  tests/unit/events/test_event_manager.py
  tests/unit/events/test_local_event_manager.py
  tests/unit/http_clients/test_curl_impersonate.py
  tests/unit/http_clients/test_httpx.py
  tests/unit/http_crawler/test_http_crawler.py
  tests/unit/memory_storage_client/test_dataset_client.py
  tests/unit/memory_storage_client/test_dataset_collection_client.py
  tests/unit/memory_storage_client/test_key_value_store_client.py
  tests/unit/memory_storage_client/test_key_value_store_collection_client.py
  tests/unit/memory_storage_client/test_request_queue_client.py
  tests/unit/memory_storage_client/test_request_queue_collection_client.py
  tests/unit/parsel_crawler/test_parsel_crawler.py
  tests/unit/sessions/test_models.py
  tests/unit/sessions/test_session.py
  tests/unit/sessions/test_session_pool.py
  tests/unit/storages/test_dataset.py
  tests/unit/storages/test_key_value_store.py
  tests/unit/storages/test_request_queue.py
Labels: t-tooling, adhoc, tested

#431 fix: Relative URLS supports & If not a URL, pass #417
  src/crawlee/_utils/urls.py
  src/crawlee/beautifulsoup_crawler/beautifulsoup_crawler.py
  src/crawlee/parsel_crawler/parsel_crawler.py
  src/crawlee/playwright_crawler/playwright_crawler.py
  tests/unit/_utils/test_urls.py
Labels: t-tooling

#450 chore: pin Docusaurus version
  website/package.json
  website/patches/@docusaurus+core+3.5.2.patch
  website/yarn.lock
Labels: t-tooling, adhoc

#452 chore: regenerate lockfile (yarn@v4)
  website/yarn.lock
Labels: t-tooling, adhoc

#447 chore: reschedule renovate bot
  renovate.json
Labels: t-tooling, adhoc

#449 docs: add links to API doc in suitable places
  README.md
  docs/examples/add-data-to-dataset.mdx
  docs/examples/beautifulsoup-crawler.mdx
  docs/examples/capture-screenshot-using-playwright.mdx
  docs/examples/crawl-all-links-on-website.mdx
  docs/examples/crawl-multiple-urls.mdx
  docs/examples/crawl-specific-links-on-website.mdx
  docs/examples/crawl-website-with-relative-links.mdx
  docs/examples/export-entire-dataset-to-file.mdx
  docs/examples/parsel-crawler.mdx
  docs/examples/playwright-crawler.mdx
  docs/guides/http_clients.mdx
  docs/guides/proxy_management.mdx
  docs/introduction/01-setting-up.mdx
  docs/introduction/02-first-crawler.mdx
  docs/introduction/03-adding-more-urls.mdx
  docs/introduction/04-real-world-project.mdx
  docs/introduction/05-crawling.mdx
  docs/introduction/06-scraping.mdx
  docs/introduction/07-saving-data.mdx
  docs/introduction/08-refactoring.mdx
  docs/introduction/index.mdx
  docs/quick-start/index.mdx
Labels: t-tooling

#453 feat: add support for filling a web form
  docs/examples/fill-and-submit-web-form.mdx
  docs/introduction/04-real-world-project.mdx
  src/crawlee/http_clients/curl_impersonate.py
  src/crawlee/http_clients/httpx.py
  src/crawlee/models.py
  website/static/img/fill-and-submit-web-form/00.jpg
  website/static/img/fill-and-submit-web-form/01.jpg
  website/static/img/fill-and-submit-web-form/02.jpg
  website/static/img/fill-and-submit-web-form/03.jpg
  website/static/img/getting-started/current-price.jpg
  website/static/img/getting-started/scraping-practice.jpg
  website/static/img/getting-started/select-an-element.jpg
  website/static/img/getting-started/select-an-element.png
  website/static/img/getting-started/selected-element.jpg
  website/static/img/getting-started/selected-element.png
  website/static/img/getting-started/sku.jpg
  website/static/img/getting-started/title.jpg
Labels: t-tooling

#454 ci: Do not skip breaking commits in changelog
  cliff.toml
Labels: t-tooling, adhoc

#458 fix: Typo in ProlongRequestLockResponse
  src/crawlee/models.py
Labels: t-tooling, adhoc

#461 refactor: storage-related models are in base storage client
  src/crawlee/__init__.py
  src/crawlee/_request.py
  src/crawlee/_types.py
  src/crawlee/_utils/system.py
  src/crawlee/base_storage_client/__init__.py
  src/crawlee/base_storage_client/_base_dataset_client.py
  src/crawlee/base_storage_client/_base_dataset_collection_client.py
  src/crawlee/base_storage_client/_base_key_value_store_client.py
  src/crawlee/base_storage_client/_base_key_value_store_collection_client.py
  src/crawlee/base_storage_client/_base_request_queue_client.py
  src/crawlee/base_storage_client/_base_request_queue_collection_client.py
  src/crawlee/base_storage_client/_models.py
  src/crawlee/basic_crawler/_basic_crawler.py
  src/crawlee/beautifulsoup_crawler/_beautifulsoup_crawler.py
  src/crawlee/http_clients/_base.py
  src/crawlee/http_clients/_httpx.py
  src/crawlee/http_clients/curl_impersonate.py
  src/crawlee/memory_storage_client/_creation_management.py
  src/crawlee/memory_storage_client/_dataset_client.py
  src/crawlee/memory_storage_client/_dataset_collection_client.py
  src/crawlee/memory_storage_client/_key_value_store_client.py
  src/crawlee/memory_storage_client/_key_value_store_collection_client.py
  src/crawlee/memory_storage_client/_request_queue_client.py
  src/crawlee/memory_storage_client/_request_queue_collection_client.py
  src/crawlee/parsel_crawler/_parsel_crawler.py
  src/crawlee/playwright_crawler/_playwright_crawler.py
  src/crawlee/proxy_configuration.py
  src/crawlee/sessions/_models.py
  src/crawlee/statistics/_models.py
  src/crawlee/storages/_dataset.py
  src/crawlee/storages/_key_value_store.py
  src/crawlee/storages/_request_list.py
  src/crawlee/storages/_request_provider.py
  src/crawlee/storages/_request_queue.py
  tests/unit/_memory_storage_client/test_key_value_store_client.py
  tests/unit/basic_crawler/test_basic_crawler.py
  tests/unit/parsel_crawler/test_parsel_crawler.py
  tests/unit/storages/test_request_queue.py
Labels: t-tooling, adhoc, debt

#462 docs: unpin Docusaurus version, fix build
  website/package.json
  website/src/theme/DocItem/Layout/index.js
  website/src/theme/DocSidebar/Desktop/Content/index.js
  website/src/theme/NavbarItem/ComponentTypes.js
  website/yarn.lock
Labels: t-tooling, adhoc

#463 fix: Add missing __all__ to top-level __init__.py file
  src/crawlee/__init__.py
Labels: t-tooling, adhoc

#464 docs: add upgrading guide to v03
  docs/upgrading/upgrading_to_v03.md
  website/sidebars.js
Labels: documentation, t-tooling, adhoc

#466 ci: Skip running code checks on release
  .github/workflows/run_release.yaml
Labels: t-tooling, adhoc

#465 docs: improve docstrings of storages
  .github/workflows/check_pr_title.yaml
  .github/workflows/docs.yaml
  .github/workflows/docs.yml
  .github/workflows/run_release.yaml
  src/crawlee/_request.py
  src/crawlee/storages/_dataset.py
  src/crawlee/storages/_key_value_store.py
  src/crawlee/storages/_request_queue.py
  website/transformDocs.js
Labels: t-tooling

#467 chore: update project links & repository references
  .github/workflows/run_release.yaml
  pyproject.toml
  src/crawlee/_autoscaling/snapshotter.py
  src/crawlee/_request.py
  tests/unit/_memory_storage_client/test_memory_storage_client.py
  tests/unit/conftest.py
Labels: t-tooling, adhoc, tested

#470 chore: update phony in makefile
  Makefile
Labels: t-tooling, adhoc

#471 ci: fix update new issue trigger
  .github/workflows/update_new_issue.yaml
Labels: t-tooling, adhoc

#472 chore: remove upper version boundary of deps
  pyproject.toml
Labels: t-tooling, adhoc

#473 feat: curl http client selects chrome impersonation by default
  src/crawlee/http_clients/curl_impersonate.py
Labels: enhancement, t-tooling, adhoc

#474 chore(deps): Relax Playwright version constraint
  pyproject.toml
Labels: t-tooling, adhoc

#443 fix: double incrementation of `item_count`
  src/crawlee/memory_storage_client/_creation_management.py
  tests/unit/_memory_storage_client/test_dataset_client.py
Labels: t-tooling
