Repository apify/crawlee-python, pull requests merged in 2024-09, with the labels that each got.

#485 fix: field alias in `BatchRequestsOperationResponse`
  src/crawlee/base_storage_client/_models.py
Labels: t-tooling, adhoc

#483 chore(deps): Relax pyee dependency version constraint
  pyproject.toml
Labels: t-tooling, adhoc

#499 fix: Deduplicate requests by unique key before submitting them to the queue
  src/crawlee/storages/_request_provider.py
Labels: t-tooling, adhoc

#500 chore: Do not install poetry in install-dev make target
  .github/workflows/_check_changelog_entry.yaml
  .github/workflows/_check_docs_build.yaml
  .github/workflows/_linting.yaml
  .github/workflows/_publish_to_pypi.yaml
  .github/workflows/_type_checking.yaml
  .github/workflows/_unit_tests.yaml
  .github/workflows/docs.yaml
  Makefile
Labels: t-tooling, adhoc

#501 fix: expose basic crawling context
  src/crawlee/basic_crawler/__init__.py
Labels: t-tooling, adhoc

#498 fix: http clients detect 4xx as errors by default
  src/crawlee/_utils/http.py
  src/crawlee/basic_crawler/_basic_crawler.py
  src/crawlee/errors.py
  src/crawlee/http_clients/_base.py
  src/crawlee/http_clients/_httpx.py
  src/crawlee/http_clients/curl_impersonate.py
  tests/unit/http_crawler/test_http_crawler.py
  tests/unit/parsel_crawler/test_parsel_crawler.py
Labels: t-tooling, tested

#507 docs: add intercom messenger
  website/docusaurus.config.js
Labels: t-web

#504 refactor: simplify type of request(s) args
  src/crawlee/basic_crawler/_basic_crawler.py
  src/crawlee/storages/_request_list.py
  src/crawlee/storages/_request_provider.py
  src/crawlee/storages/_request_queue.py
  tests/unit/storages/test_request_queue.py
Labels: t-tooling, adhoc, tested

#508 fix: Correctly handle log level configuration
  src/crawlee/_log_config.py
  src/crawlee/basic_crawler/_basic_crawler.py
  src/crawlee/configuration.py
Labels: t-tooling, adhoc

#513 feat: add HTTP/2 support for HTTPX client
  pyproject.toml
  src/crawlee/http_clients/_base.py
  src/crawlee/http_clients/_httpx.py
  src/crawlee/http_clients/curl_impersonate.py
  tests/unit/http_clients/test_httpx.py
Labels: t-tooling, tested

#482 docs: Deployment guide
  docs/deployment/apify_platform.mdx
  docs/deployment/code/apify_platform_get_public_url.py
  docs/deployment/code/apify_platform_main.py
  docs/introduction/09_running_in_cloud.mdx
  docs/introduction/code/09_apify_sdk.py
  docs/introduction/code/__init__.py
  docs/introduction/code/routes.py
  pyproject.toml
  templates/beautifulsoup/.dockerignore
  templates/beautifulsoup/.gitignore
  templates/beautifulsoup/Dockerfile
  templates/playwright/.dockerignore
  templates/playwright/.gitignore
  templates/playwright/Dockerfile
  website/sidebars.js
Labels: t-tooling, adhoc

#518 refactor: use same file structure as in Actor templates
  templates/beautifulsoup/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/__main__.py
  templates/beautifulsoup/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/main.py
  templates/beautifulsoup/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/routes.py
  templates/playwright/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/__main__.py
  templates/playwright/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/main.py
  templates/playwright/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/routes.py
Labels: t-tooling

#519 chore: rm non-existing typer extra
  pyproject.toml
Labels: t-tooling, adhoc

#529 ci: allow beta releases for chore commits
  .github/workflows/run_release.yaml
Labels: bug, t-tooling, adhoc

#521 docs: add request storage guide
  docs/guides/code/request_storage_do_not_purge.py
  docs/guides/code/request_storage_helper_add_requests.py
  docs/guides/code/request_storage_helper_enqueue_links.py
  docs/guides/code/request_storage_purge_explicitly.py
  docs/guides/code/request_storage_rl_basic.py
  docs/guides/code/request_storage_rl_with_crawler.py
  docs/guides/code/request_storage_rq_basic.py
  docs/guides/code/request_storage_rq_with_crawler.py
  docs/guides/code/request_storage_rq_with_crawler_explicit.py
  docs/guides/request_storage.mdx
Labels: t-tooling

#530 feat: add header generator and integrate it into HTTPX client
  src/crawlee/fingerprint_suite/__init__.py
  src/crawlee/fingerprint_suite/_consts.py
  src/crawlee/fingerprint_suite/_header_generator.py
  src/crawlee/fingerprint_suite/py.typed
  src/crawlee/http_clients/_httpx.py
  tests/unit/fingerprint_suite/test_header_generator.py
  tests/unit/http_clients/test_httpx.py
Labels: t-tooling, tested

#534 docs: improve docstring of Request class
  src/crawlee/_request.py
Labels: documentation, t-tooling, adhoc

#533 fix: use explicitly UTF-8 encoding in local storage
  src/crawlee/memory_storage_client/_dataset_client.py
  src/crawlee/memory_storage_client/_request_queue_client.py
Labels: t-tooling

#540 fix: Improve `Request.user_data` serialization
  src/crawlee/_request.py
  tests/unit/basic_crawler/test_basic_crawler.py
  tests/unit/storages/test_request_queue.py
Labels: t-tooling, tested

#543 fix: adopt new version of curl-cffi
  pyproject.toml
  src/crawlee/_request.py
  src/crawlee/_types.py
  src/crawlee/_utils/http.py
  src/crawlee/_utils/requests.py
  src/crawlee/fingerprint_suite/_consts.py
  src/crawlee/http_clients/_base.py
  src/crawlee/http_clients/_httpx.py
  src/crawlee/http_clients/curl_impersonate.py
  src/crawlee/memory_storage_client/_request_queue_client.py
  src/crawlee/playwright_crawler/_utils.py
  tests/unit/_utils/test_requests.py
  tests/unit/fingerprint_suite/test_header_generator.py
  tests/unit/proxy_configuration/test_tiers.py
  tests/unit/test_service_container.py
Labels: bug, t-tooling, adhoc, tested

#545 feat: mask Playwright's "headless" headers
  src/crawlee/_types.py
  src/crawlee/browsers/_base_browser_controller.py
  src/crawlee/browsers/_base_browser_plugin.py
  src/crawlee/browsers/_browser_pool.py
  src/crawlee/browsers/_playwright_browser_controller.py
  src/crawlee/browsers/_playwright_browser_plugin.py
  src/crawlee/browsers/_types.py
  src/crawlee/fingerprint_suite/_consts.py
  src/crawlee/fingerprint_suite/_header_generator.py
  src/crawlee/http_clients/_httpx.py
  src/crawlee/playwright_crawler/_playwright_crawler.py
  src/crawlee/storages/_dataset.py
  tests/unit/fingerprint_suite/test_header_generator.py
  tests/unit/http_clients/test_httpx.py
  tests/unit/playwright_crawler/test_playwright_crawler.py
Labels: t-tooling, tested
