Repository apify/crawlee-python, pull requests merged in 2024-07, with the labels that each got.

#253 doc: add 3 more pages to the introduction doc section
  docs/introduction/04-real-world-project.md
  docs/introduction/05-crawling.md
  docs/introduction/06-scraping.md
  website/sidebars.js
Labels: t-tooling, tested

#252 doc: Add examples
  docs/examples/add-data-to-dataset.md
  docs/examples/crawl-all-links-on-a-website.md
  docs/examples/export-dataset-to-csv.md
  docs/examples/http-crawler.md
Labels: t-tooling, adhoc

#255 doc: add 2 last pages to the introduction doc section
  docs/introduction/06-scraping.md
  docs/introduction/07-saving-data.md
  docs/introduction/08-refactoring.md
  docs/introduction/09-running-in-cloud.md
  website/sidebars.js
Labels: t-tooling

#258 ci: setup branch auto-merge via renovate
  renovate.json
  website/package.json
  website/yarn.lock
Labels: t-tooling, adhoc

#262 docs: autogenerated api docs
  .github/workflows/docs.yml
  Makefile
  website/build_api_reference.sh
  website/docusaurus.config.js
  website/generate_module_shortcuts.py
  website/package-lock.json
  website/package.json
  website/pydoc-markdown.yml
  website/transformDocs.js
  website/yarn.lock
Labels: t-tooling, adhoc

#264 doc: final readme for public launch
  README.md
Labels: documentation, t-tooling, adhoc

#265 docs: fix packages installation in CI docs build
  .github/workflows/_check_docs_build.yaml
  .github/workflows/docs.yml
  website/build_api_reference.sh
Labels: t-tooling, adhoc

#271 fix: CLI UX improvements
  src/crawlee/cli.py
  src/crawlee/http_clients/httpx_client.py
  website/generate_module_shortcuts.py
Labels: t-tooling

#273 fix: error handling in CLI and templates documentation
  .github/pull_request_template.md
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  docs/introduction/01-setting-up.md
  docs/quick-start/index.md
  pyproject.toml
  src/crawlee/__init__.py
  src/crawlee/cli.py
  src/crawlee/configuration.py
  src/crawlee/memory_storage_client/memory_storage_client.py
  src/crawlee/storages/dataset.py
  src/crawlee/storages/key_value_store.py
  src/crawlee/storages/request_queue.py
  templates/beautifulsoup/{{cookiecutter.project_name}}/README.md
  templates/beautifulsoup/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/routes.py
  templates/playwright/{{cookiecutter.project_name}}/README.md
  templates/playwright/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/routes.py
  tests/unit/conftest.py
  tests/unit/memory_storage_client/test_memory_storage_client.py
Labels: t-tooling, adhoc, tested

#276 docs: port proxy configuration guide
  docs/guides/proxy_management.mdx
  docs/guides/proxy_management_inspection_beautifulsoup.py
  docs/guides/proxy_management_inspection_http.py
  docs/guides/proxy_management_inspection_playwright.py
  docs/guides/proxy_management_integration_beautifulsoup.py
  docs/guides/proxy_management_integration_http.py
  docs/guides/proxy_management_integration_playwright.py
  docs/guides/proxy_management_session_beautifulsoup.py
  docs/guides/proxy_management_session_http.py
  docs/guides/proxy_management_session_playwright.py
  website/sidebars.js
  website/src/components/ApiLink.jsx
Labels: t-tooling, adhoc

#277 chore: bump version to 0.1.1
  CHANGELOG.md
  README.md
  pyproject.toml
  src/crawlee/__init__.py
Labels: t-tooling, adhoc

#278 doc: improve guide proxy management
  docs/examples/add-data-to-dataset.mdx
  docs/examples/beautifulsoup-crawler.mdx
  docs/examples/capture-screenshot-using-playwright.mdx
  docs/examples/crawl-all-links-on-website.mdx
  docs/examples/crawl-multiple-urls.mdx
  docs/examples/crawl-specific-links-on-website.mdx
  docs/examples/crawl-website-with-relative-links.mdx
  docs/examples/export-entire-dataset-to-file.mdx
  docs/examples/playwright-crawler.mdx
  docs/guides/proxy_management.mdx
  docs/guides/proxy_management_examples/inspecting_beautifulsoup.py
  docs/guides/proxy_management_examples/inspecting_playwright.py
  docs/guides/proxy_management_examples/integration_beautifulsoup.py
  docs/guides/proxy_management_examples/integration_playwright.py
  docs/guides/proxy_management_examples/quick_start.py
  docs/guides/proxy_management_examples/session_beautifulsoup.py
  docs/guides/proxy_management_examples/session_playwright.py
  docs/guides/proxy_management_inspection_beautifulsoup.py
  docs/guides/proxy_management_inspection_http.py
  docs/guides/proxy_management_inspection_playwright.py
  docs/guides/proxy_management_integration_beautifulsoup.py
  docs/guides/proxy_management_integration_http.py
  docs/guides/proxy_management_integration_playwright.py
  docs/guides/proxy_management_session_beautifulsoup.py
  docs/guides/proxy_management_session_http.py
  docs/guides/proxy_management_session_playwright.py
  docs/introduction/01-setting-up.mdx
  docs/introduction/02-first-crawler.mdx
  docs/introduction/03-adding-more-urls.mdx
  docs/introduction/04-real-world-project.mdx
  docs/introduction/05-crawling.mdx
  docs/introduction/06-scraping.mdx
  docs/introduction/07-saving-data.mdx
  docs/introduction/08-refactoring.mdx
  docs/introduction/09-running-in-cloud.mdx
  docs/introduction/index.mdx
  docs/quick-start/index.mdx
Labels: documentation, t-tooling, adhoc

#279 chore: renovate bot updates only dev deps
  renovate.json
Labels: t-tooling, adhoc

#288 chore: no explicit version in init file
  src/crawlee/__init__.py
Labels: t-tooling, adhoc

#289 chore: alphabetize and format dependencies
  pyproject.toml
Labels: t-tooling, adhoc

#290 chore: fix links on PyPI
  pyproject.toml
Labels: t-tooling, adhoc

#274 chore: update check changelog entry script
  .github/workflows/run_code_checks.yaml
  scripts/check_changelog_entry.py
Labels: t-tooling, adhoc

#308 doc: improve installation section
  .gitignore
  README.md
  docs/introduction/01-setting-up.mdx
Labels: t-tooling, adhoc

#313 fix: Pylance reportPrivateImportUsage errors
  CHANGELOG.md
  src/crawlee/autoscaling/__init__.py
  src/crawlee/base_storage_client/__init__.py
  src/crawlee/basic_crawler/__init__.py
  src/crawlee/beautifulsoup_crawler/__init__.py
  src/crawlee/browsers/__init__.py
  src/crawlee/events/__init__.py
  src/crawlee/http_clients/__init__.py
  src/crawlee/http_crawler/__init__.py
  src/crawlee/memory_storage_client/__init__.py
  src/crawlee/playwright_crawler/__init__.py
  src/crawlee/sessions/__init__.py
  src/crawlee/statistics/__init__.py
  src/crawlee/storages/__init__.py
Labels: t-tooling

#314 fix: set httpx logging to warning
  CHANGELOG.md
  src/crawlee/basic_crawler/basic_crawler.py
Labels: t-tooling

#323 chore: add doc-related commands to contributing and makefile
  CONTRIBUTING.md
  Makefile
  pyproject.toml
Labels: t-tooling, adhoc

#320 doc: tiered proxy urls
  docs/guides/proxy_management.mdx
  docs/guides/proxy_management_examples/tiers_beautifulsoup.py
  docs/guides/proxy_management_examples/tiers_playwright.py
  src/crawlee/proxy_configuration.py
Labels: t-tooling

#245 fix: byte size serialization in MemoryInfo
  src/crawlee/_utils/system.py
Labels: t-tooling, adhoc

#318 fix: project bootstrapping in existing folder
  CHANGELOG.md
  src/crawlee/cli.py
  tests/unit/cli/test_create.py
Labels: t-tooling, tested

#328 feat: blocking detection for playwright crawler
  CHANGELOG.md
  src/crawlee/basic_crawler/types.py
  src/crawlee/playwright_crawler/playwright_crawler.py
  src/crawlee/playwright_crawler/types.py
Labels: t-tooling

#329 chore: bump version to 0.1.2
  CHANGELOG.md
  pyproject.toml
Labels: t-tooling, adhoc

#331 fix: Also use error_handler for context pipeline errors
  src/crawlee/basic_crawler/basic_crawler.py
  src/crawlee/playwright_crawler/playwright_crawler.py
  tests/unit/playwright_crawler/test_playwright_crawler.py
Labels: t-tooling, tested

#346 fix: Strip whitespace from href in enqueue_links
  src/crawlee/beautifulsoup_crawler/beautifulsoup_crawler.py
  src/crawlee/playwright_crawler/playwright_crawler.py
Labels: t-tooling

#343 feat: add URL validation
  CHANGELOG.md
  src/crawlee/_utils/urls.py
  src/crawlee/basic_crawler/basic_crawler.py
  src/crawlee/beautifulsoup_crawler/beautifulsoup_crawler.py
  src/crawlee/http_clients/httpx_client.py
  src/crawlee/models.py
  src/crawlee/playwright_crawler/playwright_crawler.py
  src/crawlee/proxy_configuration.py
  tests/unit/_utils/test_urls.py
  tests/unit/basic_crawler/test_basic_crawler.py
  tests/unit/basic_crawler/test_context_pipeline.py
  tests/unit/basic_crawler/test_router.py
  tests/unit/beautifulsoup_crawler/test_beautifulsoup_crawler.py
  tests/unit/http_crawler/test_http_crawler.py
  tests/unit/memory_storage_client/test_request_queue_client.py
  tests/unit/playwright_crawler/test_playwright_crawler.py
  tests/unit/storages/test_request_queue.py
Labels: t-tooling, tested

#353 refactor: `context.request.url` is string
  src/crawlee/_utils/urls.py
  src/crawlee/basic_crawler/basic_crawler.py
  src/crawlee/beautifulsoup_crawler/beautifulsoup_crawler.py
  src/crawlee/http_clients/httpx_client.py
  src/crawlee/models.py
  src/crawlee/playwright_crawler/playwright_crawler.py
  src/crawlee/proxy_configuration.py
  tests/unit/_utils/test_urls.py
  tests/unit/basic_crawler/test_basic_crawler.py
  tests/unit/beautifulsoup_crawler/test_beautifulsoup_crawler.py
  tests/unit/http_crawler/test_http_crawler.py
  tests/unit/memory_storage_client/test_request_queue_client.py
  tests/unit/playwright_crawler/test_playwright_crawler.py
  tests/unit/storages/test_request_queue.py
Labels: t-tooling, adhoc, tested

#342 fix: Warn instead of crashing when an empty dataset is being exported
  src/crawlee/storages/dataset.py
Labels: t-tooling

#330 ci: autogenerate changelog
  .github/pull_request_template.md
  .github/workflows/_publish_to_pypi.yaml
  .github/workflows/check_pr_title.yaml
  .github/workflows/run_code_checks.yaml
  .github/workflows/run_release.yaml
  .pre-commit-config.yaml
  CHANGELOG.md
  Makefile
  cliff.toml
  scripts/check_changelog_entry.py
Labels: t-tooling

#360 ci: fix condition
  .github/workflows/run_release.yaml
Labels: t-tooling, adhoc

#361 ci: fix variable access
  .github/workflows/run_release.yaml
Labels: t-tooling, adhoc

#362 ci: fix comparison, install git-cliff from pypi
  .github/workflows/run_release.yaml
Labels: t-tooling, adhoc

#363 ci: missing 'fi'
  .github/workflows/run_release.yaml
Labels: t-tooling, adhoc

#364 fix: Avoid Github rate limiting in project bootstrapping test
  .github/workflows/_unit_tests.yaml
  src/crawlee/cli.py
Labels: t-tooling, adhoc

#365 ci: Use service account token in changelog update workflow
  .github/workflows/run_release.yaml
Labels: t-tooling, adhoc

#366 ci: Fix version number variable name
  .github/workflows/run_release.yaml
Labels: t-tooling, adhoc

#367 ci: Fix output handling
  .github/workflows/run_release.yaml
Labels: t-tooling, adhoc

#368 ci: Fix version number job output
  .github/workflows/run_release.yaml
Labels: t-tooling, adhoc

#357 chore: add basic badges to readme
  README.md
Labels: t-tooling, adhoc

#375 fix: pass crawler configuration to storages
  src/crawlee/basic_crawler/basic_crawler.py
  tests/unit/basic_crawler/test_basic_crawler.py
Labels: t-tooling, adhoc, tested

#377 fix: purge request queue on repeated crawler runs
  src/crawlee/basic_crawler/basic_crawler.py
  tests/unit/basic_crawler/test_basic_crawler.py
Labels: t-tooling, tested

#380 ci: Add missing job dependency
  .github/workflows/run_release.yaml
Labels: t-tooling, adhoc

#381 ci: Do not fail with no changes in changelog
  .github/workflows/run_release.yaml
Labels: t-tooling, adhoc

#382 chore(release): Bump version
  pyproject.toml
Labels: t-tooling, adhoc

#383 test: Test persist_storage more thoroughly
  tests/unit/basic_crawler/test_basic_crawler.py
  tests/unit/memory_storage_client/test_memory_storage_client.py
Labels: t-tooling, adhoc, tested
