Repository apify/crawlee-python, pull requests merged in 2024-12, with the labels that each got.

#775 fix: add upper bound of HTTPX version
  poetry.lock
  pyproject.toml
Labels: t-tooling, adhoc

#772 docs: Improve the Features section in README
  README.md
Labels: documentation, t-tooling, adhoc

#780 fix: Fix incorrect use of desired concurrency ratio
  src/crawlee/_autoscaling/autoscaled_pool.py
  tests/unit/_autoscaling/test_autoscaled_pool.py
Labels: bug, t-tooling, tested

#757 fix: Remove pydantic constraint <2.10.0 and update timedelta validator, serializer type hints
  poetry.lock
  pyproject.toml
  src/crawlee/_utils/models.py
  tests/unit/_utils/test_timedelata_ms.py
Labels: t-tooling, debt, tested

#784 ci: Prepend to changelog on (pre)release
  .github/workflows/pre_release.yaml
  .github/workflows/release.yaml
Labels: t-tooling, adhoc

#785 docs: Fix changelog
  CHANGELOG.md
Labels: t-tooling, adhoc

#746 refactor!: Refactor HttpCrawler, BeautifulSoupCrawler, ParselCrawler inheritance
  docs/guides/http_crawlers.mdx
  src/crawlee/abstract_http_crawler/__init__.py
  src/crawlee/abstract_http_crawler/_abstract_http_crawler.py
  src/crawlee/abstract_http_crawler/_abstract_http_parser.py
  src/crawlee/abstract_http_crawler/_http_crawling_context.py
  src/crawlee/basic_crawler/__init__.py
  src/crawlee/basic_crawler/_blocked_info.py
  src/crawlee/beautifulsoup_crawler/__init__.py
  src/crawlee/beautifulsoup_crawler/_beautifulsoup_crawler.py
  src/crawlee/beautifulsoup_crawler/_beautifulsoup_crawling_context.py
  src/crawlee/beautifulsoup_crawler/_beautifulsoup_parser.py
  src/crawlee/http_clients/_base.py
  src/crawlee/http_crawler/__init__.py
  src/crawlee/http_crawler/_http_crawler.py
  src/crawlee/http_crawler/_http_crawling_context.py
  src/crawlee/http_crawler/_http_parser.py
  src/crawlee/parsel_crawler/_parsel_crawler.py
  src/crawlee/parsel_crawler/_parsel_crawling_context.py
  src/crawlee/parsel_crawler/_parsel_parser.py
  tests/unit/beautifulsoup_crawler/test_beautifulsoup_crawler.py
  tests/unit/http_crawler/test_http_crawler.py
Labels: t-tooling, debt, tested

#793 chore: Remove apify dependency
  poetry.lock
  pyproject.toml
  src/crawlee/project_template/{{cookiecutter.project_name}}/_pyproject.toml
  src/crawlee/project_template/{{cookiecutter.project_name}}/requirements.txt
Labels: t-tooling, adhoc

#760 feat: Add possibility to use None as no proxy in tiered proxies
  docs/guides/code/proxy_management/tiers_bs_example.py
  docs/guides/code/proxy_management/tiers_pw_example.py
  src/crawlee/proxy_configuration.py
  tests/unit/proxy_configuration/test_new_proxy_info.py
  tests/unit/proxy_configuration/test_tiers.py
Labels: enhancement, t-tooling, tested

#799 docs: Update upgrading guide for renamed BeautifulSoupParser
  docs/upgrading/upgrading_to_v0x.md
Labels: documentation, t-tooling, adhoc

#682 feat: Add `use_state` context method
  src/crawlee/_types.py
  src/crawlee/basic_crawler/_basic_crawler.py
  src/crawlee/playwright_crawler/_playwright_crawler.py
  src/crawlee/storages/_key_value_store.py
  tests/unit/basic_crawler/test_basic_crawler.py
  tests/unit/basic_crawler/test_context_pipeline.py
  tests/unit/storages/test_key_value_store.py
  tests/unit/test_router.py
Labels: enhancement, t-tooling

#794 chore: Skip flaky test
  tests/unit/basic_crawler/test_basic_crawler.py
Labels: t-tooling, tested

#803 chore: Fix format
  tests/unit/basic_crawler/test_basic_crawler.py
Labels: t-tooling, adhoc, tested

#791 feat: Add pre-navigation hooks router to AbstractHttpCrawler
  docs/examples/beautifulsoup_crawler.mdx
  docs/examples/code/beautifulsoup_crawler.py
  docs/examples/code/parsel_crawler.py
  docs/examples/parsel_crawler.mdx
  src/crawlee/abstract_http_crawler/_abstract_http_crawler.py
  tests/unit/http_crawler/test_http_crawler.py
Labels: enhancement, t-tooling, tested

#789 feat: Add example of how to integrate Camoufox into PlaywrightCrawler
  docs/examples/code/playwright_crawler_with_camoufox.py
  docs/examples/playwright_crawler_with_camoufox.mdx
  pyproject.toml
  src/crawlee/project_template/cookiecutter.json
  src/crawlee/project_template/templates/main.py
  src/crawlee/project_template/templates/main_playwright_camoufox.py
  src/crawlee/project_template/templates/routes_camoufox.py
  src/crawlee/project_template/templates/routes_playwright_camoufox.py
  src/crawlee/project_template/{{cookiecutter.project_name}}/Dockerfile
  src/crawlee/project_template/{{cookiecutter.project_name}}/_pyproject.toml
  src/crawlee/project_template/{{cookiecutter.project_name}}/requirements.txt
  src/crawlee/project_template/{{cookiecutter.project_name}}/{{cookiecutter.__package_name}}/main.py
  src/crawlee/project_template/{{cookiecutter.project_name}}/{{cookiecutter.__package_name}}/routes.py
Labels: documentation, enhancement, t-tooling

#810 chore: Update test_get_auto_saved_value_auto_save to reduce flakiness
  tests/unit/storages/test_key_value_store.py
Labels: t-tooling, adhoc, tested

#691 fix!: Refactor service usage to rely on `service_locator`
  .gitignore
  docs/guides/code/request_storage/purge_explicitly_example.py
  docs/upgrading/upgrading_to_v0x.md
  poetry.lock
  pyproject.toml
  src/crawlee/__init__.py
  src/crawlee/_autoscaling/snapshotter.py
  src/crawlee/_log_config.py
  src/crawlee/_service_locator.py
  src/crawlee/basic_crawler/_basic_crawler.py
  src/crawlee/configuration.py
  src/crawlee/errors.py
  src/crawlee/events/_event_manager.py
  src/crawlee/memory_storage_client/_creation_management.py
  src/crawlee/memory_storage_client/_memory_storage_client.py
  src/crawlee/service_container.py
  src/crawlee/sessions/_session_pool.py
  src/crawlee/statistics/_statistics.py
  src/crawlee/storages/_base_storage.py
  src/crawlee/storages/_creation_management.py
  src/crawlee/storages/_dataset.py
  src/crawlee/storages/_key_value_store.py
  src/crawlee/storages/_request_queue.py
  tests/unit/_autoscaling/test_snapshotter.py
  tests/unit/_autoscaling/test_system_status.py
  tests/unit/_memory_storage_client/test_memory_storage_client.py
  tests/unit/_memory_storage_client/test_memory_storage_e2e.py
  tests/unit/basic_crawler/test_basic_crawler.py
  tests/unit/conftest.py
  tests/unit/sessions/test_session_pool.py
  tests/unit/storages/test_key_value_store.py
  tests/unit/test_configuration.py
  tests/unit/test_service_container.py
  tests/unit/test_service_locator.py
Labels: t-tooling, tested

#823 docs: document inherited symbols properly
  website/package.json
  website/yarn.lock
Labels: documentation, t-tooling, adhoc

#800 feat: Expose event types, improve on/emit signature, allow parameterless listeners
  src/crawlee/_utils/docs.py
  src/crawlee/events/__init__.py
  src/crawlee/events/_event_manager.py
  src/crawlee/events/_types.py
  tests/unit/events/test_event_manager.py
  tests/unit/events/test_local_event_manager.py
Labels: t-tooling, tested

#788 refactor!: remove `json_` and `order_no` from `Request`
  docs/upgrading/upgrading_to_v0x.md
  src/crawlee/_request.py
  src/crawlee/_utils/data_processing.py
  src/crawlee/base_storage_client/_models.py
  src/crawlee/memory_storage_client/_creation_management.py
  src/crawlee/memory_storage_client/_request_queue_client.py
  tests/unit/_memory_storage_client/test_memory_storage_e2e.py
  tests/unit/_memory_storage_client/test_request_queue_client.py
  tests/unit/_utils/test_data_processing.py
Labels: t-tooling, debt

#825 fix: fix event migrating handler in `RequestQueue`
  src/crawlee/storages/_request_queue.py
Labels: t-tooling

#807 feat: Add stop method to BasicCrawler
  docs/examples/code/beautifulsoup_crawler_stop.py
  docs/examples/crawler_stop.mdx
  src/crawlee/basic_crawler/_basic_crawler.py
  tests/unit/basic_crawler/test_basic_crawler.py
Labels: enhancement, t-tooling, tested

#827 refactor!: Rename PwPreNavContext to PwPreNavCrawlingContext
  docs/examples/code/playwright_crawler.py
  docs/upgrading/upgrading_to_v0x.md
  src/crawlee/playwright_crawler/__init__.py
  src/crawlee/playwright_crawler/_playwright_crawler.py
  src/crawlee/playwright_crawler/_playwright_crawling_context.py
  src/crawlee/playwright_crawler/_playwright_pre_nav_crawling_context.py
Labels: t-tooling, adhoc, v0.5

#777 feat!: Implement `RequestManagerTandem`, remove `add_request` from `RequestList`, accept any iterable in `RequestList` constructor
  docs/guides/code/request_storage/rl_basic_example.py
  docs/guides/code/request_storage/rl_with_crawler_example.py
  docs/guides/code/request_storage/rq_with_crawler_explicit_example.py
  docs/guides/code/request_storage/tandem_example.py
  docs/guides/code/request_storage/tandem_example_explicit.py
  docs/guides/request_storage.mdx
  docs/introduction/code/02_bs.py
  docs/upgrading/upgrading_to_v0x.md
  src/crawlee/basic_crawler/_basic_crawler.py
  src/crawlee/request_loaders/__init__.py
  src/crawlee/request_loaders/_request_list.py
  src/crawlee/request_loaders/_request_loader.py
  src/crawlee/request_loaders/_request_manager.py
  src/crawlee/request_loaders/_request_manager_tandem.py
  src/crawlee/storages/__init__.py
  src/crawlee/storages/_request_list.py
  src/crawlee/storages/_request_provider.py
  src/crawlee/storages/_request_queue.py
  tests/unit/basic_crawler/test_basic_crawler.py
  tests/unit/beautifulsoup_crawler/test_beautifulsoup_crawler.py
  tests/unit/http_crawler/test_http_crawler.py
  tests/unit/parsel_crawler/test_parsel_crawler.py
  tests/unit/playwright_crawler/test_playwright_crawler.py
  tests/unit/storages/test_request_manager_tandem.py
Labels: t-tooling, adhoc, tested, v0.5

#831 refactor!: Rename PlaywrightCrawler kwargs: browser_options, page_options
  docs/examples/code/playwright_crawler_with_camoufox.py
  docs/upgrading/upgrading_to_v0x.md
  src/crawlee/browsers/_base_browser_controller.py
  src/crawlee/browsers/_base_browser_plugin.py
  src/crawlee/browsers/_browser_pool.py
  src/crawlee/browsers/_playwright_browser_controller.py
  src/crawlee/browsers/_playwright_browser_plugin.py
  src/crawlee/playwright_crawler/_playwright_crawler.py
  tests/unit/browsers/test_browser_pool.py
  tests/unit/browsers/test_playwright_browser_plugin.py
Labels: t-tooling, adhoc, debt, tested

#837 fix: Relax ServiceLocator restrictions
  src/crawlee/_service_locator.py
  src/crawlee/errors.py
  tests/unit/_memory_storage_client/test_memory_storage_client.py
  tests/unit/basic_crawler/test_basic_crawler.py
  tests/unit/conftest.py
  tests/unit/test_service_locator.py
Labels: t-tooling, adhoc, tested

#841 fix: Fix typo in exports
  src/crawlee/http_clients/__init__.py
Labels: t-tooling, adhoc
