Repository apify/crawlee-python, pull requests merged in 2024-10, with the labels that each got.

#558 chore: remove unit tests from pre-commit config
  .pre-commit-config.yaml
Labels: t-tooling, adhoc, infrastructure

#557 fix: call `error_handler` for `SessionError`
  src/crawlee/basic_crawler/_basic_crawler.py
  tests/unit/basic_crawler/test_basic_crawler.py
Labels: t-tooling, tested

#556 fix: extend from `StrEnum` in `RequestState` to fix serialization
  src/crawlee/_request.py
  tests/unit/_memory_storage_client/test_request_queue_client.py
  tests/unit/storages/test_request_queue.py
Labels: t-tooling, tested

#544 feat: add new model for `HttpHeaders`
  src/crawlee/_request.py
  src/crawlee/_types.py
  src/crawlee/http_clients/_base.py
  src/crawlee/http_clients/_httpx.py
  src/crawlee/http_clients/curl_impersonate.py
  tests/unit/basic_crawler/test_basic_crawler.py
  tests/unit/fingerprint_suite/test_header_generator.py
Labels: t-tooling, adhoc, debt, tested

#562 fix: Add equality check to UserData model
  src/crawlee/_request.py
Labels: t-tooling, adhoc

#566 chore: set pytest-asyncio loop scope to function
  pyproject.toml
Labels: t-tooling, adhoc

#579 ci: install Poetry to setup-python environment
  .github/workflows/_check_changelog_entry.yaml
  .github/workflows/_check_docs_build.yaml
  .github/workflows/_linting.yaml
  .github/workflows/_publish_to_pypi.yaml
  .github/workflows/_type_checking.yaml
  .github/workflows/_unit_tests.yaml
  .github/workflows/docs.yaml
  .github/workflows/run_release.yaml
Labels: bug, t-tooling, adhoc, infrastructure

#581 fix: Workaround for JSON value typing problems
  src/crawlee/_request.py
  src/crawlee/_types.py
Labels: t-tooling

#582 ci: use python version instead of executable path
  .github/workflows/_check_changelog_entry.yaml
  .github/workflows/_check_docs_build.yaml
  .github/workflows/_linting.yaml
  .github/workflows/_publish_to_pypi.yaml
  .github/workflows/_type_checking.yaml
  .github/workflows/_unit_tests.yaml
  .github/workflows/docs.yaml
  .github/workflows/run_release.yaml
Labels: t-tooling, adhoc, infrastructure

#583 ci: fix python version reference in pipx install
  .github/workflows/_check_changelog_entry.yaml
  .github/workflows/_check_docs_build.yaml
  .github/workflows/_linting.yaml
  .github/workflows/_publish_to_pypi.yaml
  .github/workflows/_type_checking.yaml
  .github/workflows/_unit_tests.yaml
  .github/workflows/docs.yaml
  .github/workflows/run_release.yaml
Labels: bug, t-tooling, adhoc, infrastructure

#584 feat: Key-value store context helpers
  src/crawlee/_types.py
  src/crawlee/basic_crawler/_basic_crawler.py
  src/crawlee/beautifulsoup_crawler/_beautifulsoup_crawler.py
  src/crawlee/http_crawler/_http_crawler.py
  src/crawlee/parsel_crawler/_parsel_crawler.py
  src/crawlee/playwright_crawler/_playwright_crawler.py
  src/crawlee/storages/_dataset.py
  tests/unit/basic_crawler/test_basic_crawler.py
  tests/unit/basic_crawler/test_context_pipeline.py
  tests/unit/test_router.py
Labels: t-tooling, adhoc, tested

#591 ci: rm unused pipeline
  .github/workflows/_check_changelog_entry.yaml
  .github/workflows/_check_docs_build.yaml
  .github/workflows/docs.yaml
Labels: t-tooling, adhoc, infrastructure

#593 ci: use shared workflows and refactor them
  .github/workflows/_check_docs_build.yaml
  .github/workflows/_linting.yaml
  .github/workflows/_publish_to_pypi.yaml
  .github/workflows/_type_checking.yaml
  .github/workflows/_unit_tests.yaml
  .github/workflows/build_and_deploy_docs.yaml
  .github/workflows/docs.yaml
  .github/workflows/run_code_checks.yaml
  .github/workflows/run_release.yaml
  Makefile
Labels: t-tooling, adhoc, infrastructure

#594 ci: fix build and deploy docs workflow
  .github/workflows/build_and_deploy_docs.yaml
Labels: t-tooling, adhoc, infrastructure

#595 chore: fix doc commands in Makefile
  Makefile
Labels: t-tooling, adhoc, infrastructure

#607 docs: try to fix the CI documentation build
  .github/workflows/build_and_deploy_docs.yaml
  Makefile
Labels: t-tooling, adhoc

#597 ci: Use the release-metadata action
  .github/workflows/_publish_to_pypi.yaml
  .github/workflows/pre_release.yaml
  .github/workflows/release.yaml
  .github/workflows/run_release.yaml
  CHANGELOG.md
  Makefile
  cliff.toml
  scripts/fetch_pr_issues.sh
  scripts/preprocess_commit_message.py
Labels: t-tooling, adhoc

#606 docs: improve autogenerated API docs
  src/crawlee/configuration.py
  website/build_api_reference.sh
  website/docusaurus.config.js
  website/package.json
  website/pydoc-markdown/__init__.py
  website/pydoc-markdown/generate_ast.py
  website/pydoc-markdown/google_docstring_processor.py
  website/src/css/custom.css
  website/transformDocs.js
  website/yarn.lock
Labels: documentation, t-tooling

#610 ci: Fix pre-release and release workflows
  .github/workflows/pre_release.yaml
  .github/workflows/release.yaml
Labels: t-tooling, adhoc

#614 fix: use strip in headers normalization
  src/crawlee/_types.py
  src/crawlee/_utils/requests.py
  tests/unit/_utils/test_requests.py
Labels: bug, t-tooling, adhoc, tested

#542 fix!: merge payload and data fields of Request
  docs/examples/code/fill_and_submit_web_form_crawler.py
  docs/examples/code/fill_and_submit_web_form_request.py
  docs/examples/fill_and_submit_web_form.mdx
  src/crawlee/_request.py
  src/crawlee/_types.py
  src/crawlee/_utils/requests.py
  src/crawlee/http_clients/_base.py
  src/crawlee/http_clients/_httpx.py
  src/crawlee/http_clients/curl_impersonate.py
  src/crawlee/memory_storage_client/_request_queue_client.py
  tests/unit/_utils/test_requests.py
  tests/unit/http_crawler/test_http_crawler.py
Labels: t-tooling, tested

#620 chore: update dev deps
  pyproject.toml
  src/crawlee/basic_crawler/_basic_crawler.py
Labels: t-tooling, adhoc

#624 docs: improve API docs of all crawlers
  src/crawlee/_request.py
  src/crawlee/basic_crawler/_basic_crawler.py
  src/crawlee/beautifulsoup_crawler/_beautifulsoup_crawler.py
  src/crawlee/http_clients/_httpx.py
  src/crawlee/http_clients/curl_impersonate.py
  src/crawlee/http_crawler/_http_crawler.py
  src/crawlee/parsel_crawler/_parsel_crawler.py
  src/crawlee/playwright_crawler/_playwright_crawler.py
  src/crawlee/storages/_dataset.py
  src/crawlee/storages/_key_value_store.py
  src/crawlee/storages/_request_queue.py
Labels: documentation, t-tooling

#623 chore: change ValueError to warning in RQClient for ID mismatch
  src/crawlee/memory_storage_client/_request_queue_client.py
Labels: t-tooling, adhoc

#632 ci: Do not run pre-release in forks
  .github/workflows/pre_release.yaml
Labels: t-tooling, adhoc

#633 docs: Update input arg docstrings of `BasicCrawler` and `EventManager`
  src/crawlee/basic_crawler/_basic_crawler.py
  src/crawlee/events/_event_manager.py
Labels: documentation, t-tooling, adhoc

#636 ci: Fix output reference
  .github/workflows/pre_release.yaml
  .github/workflows/release.yaml
Labels: t-tooling, adhoc

#565 docs: homepage changes
  website/docusaurus.config.js
  website/src/pages/index.js
Labels: t-tooling
