Repository apify/crawlee-python, pull requests merged in 2024-06, with the labels that each got.

#208 doc: add a first version of Quick start page
  README.md
  docs/quick_start.md
Labels: t-tooling

#209 chore: bump version to 0.0.6
  CHANGELOG.md
  README.md
  docs/quick_start.md
  pyproject.toml
Labels: t-tooling, adhoc

#213 fix: handling of relative URLs in add_requests
  CHANGELOG.md
  src/crawlee/basic_crawler/basic_crawler.py
  tests/unit/beautifulsoup_crawler/test_beautifulsoup_crawler.py
  tests/unit/playwright_crawler/test_playwright_crawler.py
Labels: t-tooling, tested

#219 docs: fix docs build
  .github/workflows/_check_docs_build.yaml
  docs/introduction/index.mdx
  docs/quick-start/quick-start.md
  docs/quick_start.md
  website/docusaurus.config.js
  website/src/components/ApiLink.jsx
Labels: t-tooling, adhoc

#221 docs: use `pip install crawlee` instead of `pipx` for now
  website/src/pages/index.js
  website/yarn.lock
Labels: t-tooling

#198 feat: add max requests per crawl to `BasicCrawler`
  CHANGELOG.md
  src/crawlee/autoscaling/autoscaled_pool.py
  src/crawlee/basic_crawler/basic_crawler.py
  tests/unit/basic_crawler/test_basic_crawler.py
  tests/unit/beautifulsoup_crawler/test_beautifulsoup_crawler.py
Labels: t-tooling, tested

#227 chore: skip test proxy disabled on windows
  tests/unit/httpx_client/test_httpx_client.py
Labels: t-tooling, adhoc, tested

#222 feat: BasicCrawler.export_data helper
  CHANGELOG.md
  src/crawlee/basic_crawler/basic_crawler.py
  src/crawlee/storages/dataset.py
  tests/unit/basic_crawler/test_basic_crawler.py
Labels: t-tooling, tested

#229 feat: automatic logging setup
  CHANGELOG.md
  src/crawlee/basic_crawler/basic_crawler.py
  src/crawlee/basic_crawler/types.py
  src/crawlee/beautifulsoup_crawler/beautifulsoup_crawler.py
  src/crawlee/http_crawler/http_crawler.py
  src/crawlee/playwright_crawler/playwright_crawler.py
  tests/unit/basic_crawler/test_context_pipeline.py
  tests/unit/basic_crawler/test_router.py
Labels: t-tooling, tested

#233 chore: bump version to 0.0.7
  CHANGELOG.md
  CONTRIBUTING.md
  pyproject.toml
  src/crawlee/__init__.py
Labels: t-tooling, adhoc

#235 fix: do not wait for consistency in request queue
  src/crawlee/storages/request_queue.py
Labels: bug, t-tooling, adhoc

#238 ci: Check format
  Makefile
Labels: t-tooling, adhoc

#231 fix: Selector handling in BeautifulSoupCrawler enqueue_links
  CHANGELOG.md
  src/crawlee/beautifulsoup_crawler/beautifulsoup_crawler.py
  tests/unit/beautifulsoup_crawler/test_beautifulsoup_crawler.py
Labels: t-tooling, tested

#240 chore: skip test proxy on windows
  tests/unit/httpx_client/test_httpx_client.py
Labels: t-tooling, adhoc, tested

#241 fix: Improve AutoscaledPool state management
  src/crawlee/autoscaling/autoscaled_pool.py
Labels: t-tooling

#242 chore: bump version to 0.0.8
  CHANGELOG.md
  pyproject.toml
  src/crawlee/__init__.py
Labels: t-tooling, adhoc

#243 doc: add first pages of introduction section
  docs/introduction/01-setting-up.md
  docs/introduction/02-first-crawler.md
  docs/introduction/03-adding-more-urls.md
  docs/introduction/index.md
  docs/introduction/index.mdx
  docs/quick-start/index.md
  website/sidebars.js
Labels: documentation, t-tooling

#246 doc: Adjustments in introduction article
  docs/introduction/02-first-crawler.md
  docs/introduction/03-adding-more-urls.md
Labels: t-tooling, adhoc

#237 feat: Project templates
  CHANGELOG.md
  pyproject.toml
  src/crawlee/cli.py
  templates/beautifulsoup/cookiecutter.json
  templates/beautifulsoup/{{cookiecutter.project_name}}/README.md
  templates/beautifulsoup/{{cookiecutter.project_name}}/pyproject.toml
  templates/beautifulsoup/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/__init__.py
  templates/beautifulsoup/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/__main__.py
  templates/beautifulsoup/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/routes.py
  templates/playwright/cookiecutter.json
  templates/playwright/{{cookiecutter.project_name}}/README.md
  templates/playwright/{{cookiecutter.project_name}}/pyproject.toml
  templates/playwright/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/__init__.py
  templates/playwright/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/__main__.py
  templates/playwright/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/routes.py
  website/src/pages/index.js
Labels: t-tooling

#251 chore: use latest crawlee version in templates
  templates/beautifulsoup/{{cookiecutter.project_name}}/pyproject.toml
  templates/playwright/{{cookiecutter.project_name}}/pyproject.toml
Labels: t-tooling, adhoc

#250 docs: update contributing guide
  CONTRIBUTING.md
Labels: documentation, t-tooling, adhoc
