Repository apify/crawlee-python, pull requests merged in 2025-01, with the labels that each got.

#854 chore: Fix new dir structure-related issues
  docs/upgrading/upgrading_to_v0x.md
  src/crawlee/browsers/__init__.py
  src/crawlee/crawlers/_abstract_http/_abstract_http_crawler.py
  src/crawlee/crawlers/_beautifulsoup/__init__.py
  src/crawlee/crawlers/_beautifulsoup/_beautifulsoup_crawler.py
  src/crawlee/crawlers/_http/_http_crawler.py
  src/crawlee/crawlers/_parsel/__init__.py
  src/crawlee/crawlers/_parsel/_parsel_crawler.py
  src/crawlee/crawlers/_playwright/__init__.py
  src/crawlee/crawlers/_playwright/_playwright_crawler.py
  src/crawlee/crawlers/_types.py
  src/crawlee/http_clients/__init__.py
  src/crawlee/http_clients/_curl_impersonate.py
  src/crawlee/http_clients/_httpx.py
  tests/unit/crawlers/_parsel/test_parsel_crawler.py
Labels: t-tooling, adhoc, tested

#859 chore: revert React 19 bump
  website/package.json
  website/yarn.lock
Labels: t-tooling, adhoc

#865 docs: Fix crawler imports in readme
  README.md
Labels: bug, documentation, adhoc

#876 fix: Make result of RequestList.is_empty independent of fetch_next_request calls
  src/crawlee/request_loaders/_request_list.py
  tests/unit/request_loaders/test_request_list.py
Labels: t-tooling, adhoc, tested

#883 docs: fix multiline `Args` documentation
  src/crawlee/crawlers/_playwright/_playwright_crawler.py
  website/package.json
  website/yarn.lock
Labels: t-tooling, adhoc

#892 ci: Add workflow dispatch for pre-release workflow
  .github/workflows/pre_release.yaml
Labels: t-tooling, adhoc, infrastructure

#868 fix: Avoid `use_state` race conditions. Remove key argument to `use_state`
  src/crawlee/_types.py
  src/crawlee/crawlers/_basic/_basic_crawler.py
  src/crawlee/storages/_key_value_store.py
  tests/unit/crawlers/_basic/test_basic_crawler.py
  tests/unit/storages/test_key_value_store.py
Labels: bug, t-tooling, tested

#896 docs: Add Storages & Request loaders guides
  docs/guides/code/request_loaders/rl_basic_example.py
  docs/guides/code/request_loaders/tandem_example.py
  docs/guides/code/request_loaders/tandem_example_explicit.py
  docs/guides/code/request_storage/rl_with_crawler_example.py
  docs/guides/code/request_storage/tandem_example.py
  docs/guides/code/storages/cleaning_do_not_purge_example.py
  docs/guides/code/storages/cleaning_purge_explicitly_example.py
  docs/guides/code/storages/dataset_basic_example.py
  docs/guides/code/storages/dataset_with_crawler_example.py
  docs/guides/code/storages/dataset_with_crawler_explicit_example.py
  docs/guides/code/storages/helper_add_requests_example.py
  docs/guides/code/storages/helper_enqueue_links_example.py
  docs/guides/code/storages/kvs_basic_example.py
  docs/guides/code/storages/kvs_with_crawler_example.py
  docs/guides/code/storages/kvs_with_crawler_explicit_example.py
  docs/guides/code/storages/rq_basic_example.py
  docs/guides/code/storages/rq_with_crawler_example.py
  docs/guides/code/storages/rq_with_crawler_explicit_example.py
  docs/guides/request_loaders.mdx
  docs/guides/request_storage.mdx
  docs/guides/result_storage.mdx
  docs/guides/storages.mdx
  website/docusaurus.config.js
  website/package.json
  website/yarn.lock
Labels: t-tooling

#904 docs: update request loaders & storages guide
  docs/guides/request_loaders.mdx
  docs/guides/storages.mdx
Labels: documentation, t-tooling, adhoc

#899 fix: Fix the usage of Configuration
  src/crawlee/_autoscaling/snapshotter.py
  src/crawlee/_service_locator.py
  src/crawlee/browsers/_playwright_browser_plugin.py
  src/crawlee/configuration.py
  src/crawlee/crawlers/_basic/_basic_crawler.py
  src/crawlee/events/_local_event_manager.py
  src/crawlee/storage_clients/_memory/_memory_storage_client.py
  tests/unit/_autoscaling/test_snapshotter.py
  tests/unit/_autoscaling/test_system_status.py
  tests/unit/browsers/test_playwright_browser_plugin.py
  tests/unit/conftest.py
  tests/unit/crawlers/_basic/test_basic_crawler.py
Labels: t-tooling, tested

#911 chore: Convert unused AP input args into class consts
  src/crawlee/_autoscaling/autoscaled_pool.py
  src/crawlee/crawlers/_basic/_basic_crawler.py
  tests/unit/_autoscaling/test_autoscaled_pool.py
Labels: t-tooling, adhoc, tested

#914 docs: Update API docs of public components
  docs/guides/code/storages/rq_with_crawler_example.py
  docs/guides/code/storages/rq_with_crawler_explicit_example.py
  src/crawlee/_autoscaling/snapshotter.py
  src/crawlee/_types.py
  src/crawlee/_utils/http.py
  src/crawlee/browsers/_base_browser_controller.py
  src/crawlee/browsers/_base_browser_plugin.py
  src/crawlee/browsers/_browser_pool.py
  src/crawlee/browsers/_playwright_browser_controller.py
  src/crawlee/browsers/_playwright_browser_plugin.py
  src/crawlee/configuration.py
  src/crawlee/crawlers/_basic/_basic_crawler.py
  src/crawlee/events/_event_manager.py
  src/crawlee/events/_local_event_manager.py
  src/crawlee/request_loaders/_request_loader.py
  src/crawlee/sessions/_session.py
  src/crawlee/sessions/_session_pool.py
  src/crawlee/statistics/_statistics.py
  src/crawlee/storage_clients/_memory/_memory_storage_client.py
  src/crawlee/storages/_dataset.py
Labels: t-tooling

#909 fix: Fix crawler not retrying user handler if there was timeout in the handler
  src/crawlee/crawlers/_basic/_basic_crawler.py
  tests/unit/crawlers/_basic/test_basic_crawler.py
Labels: bug, t-tooling, tested

#915 docs: Fix Playwright + Camoufox code example
  docs/examples/code/playwright_crawler_with_camoufox.py
Labels: bug, documentation, t-tooling, adhoc

#916 docs: add guide for PlaywrightCrawler and BrowserPool
  docs/guides/code/playwright_crawler/browser_configuration_example.py
  docs/guides/code/playwright_crawler/multiple_launch_example.py
  docs/guides/code/playwright_crawler/plugin_browser_configuration_example.py
  docs/guides/code/playwright_crawler/pre_navigation_hook_example.py
  docs/guides/playwright_crawler.mdx
Labels: documentation, t-tooling

#922 chore: rm old templates directory
  templates/beautifulsoup/.dockerignore
  templates/beautifulsoup/.gitignore
  templates/beautifulsoup/Dockerfile
  templates/beautifulsoup/cookiecutter.json
  templates/beautifulsoup/{{cookiecutter.project_name}}/README.md
  templates/beautifulsoup/{{cookiecutter.project_name}}/pyproject.toml
  templates/beautifulsoup/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/__init__.py
  templates/beautifulsoup/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/__main__.py
  templates/beautifulsoup/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/main.py
  templates/beautifulsoup/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/routes.py
  templates/playwright/.dockerignore
  templates/playwright/.gitignore
  templates/playwright/Dockerfile
  templates/playwright/cookiecutter.json
  templates/playwright/{{cookiecutter.project_name}}/README.md
  templates/playwright/{{cookiecutter.project_name}}/pyproject.toml
  templates/playwright/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/__init__.py
  templates/playwright/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/__main__.py
  templates/playwright/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/main.py
  templates/playwright/{{cookiecutter.project_name}}/{{cookiecutter.project_name}}/routes.py
Labels: t-tooling, adhoc

#921 feat: Add keep_alive flag to `crawler.__init__`
  docs/examples/code/beautifulsoup_crawler_keep_alive.py
  docs/examples/crawler_keep_alive.mdx
  src/crawlee/crawlers/_basic/_basic_crawler.py
  tests/unit/crawlers/_basic/test_basic_crawler.py
Labels: enhancement, t-tooling, tested

#926 docs: bump `docusaurus-plugin-typedoc-api`
  website/package.json
  website/src/css/custom.css
  website/yarn.lock
Labels: t-tooling, adhoc

#940 feat: add `time_remaining_secs` property to `MIGRATING` event data
  src/crawlee/_utils/models.py
  src/crawlee/events/_types.py
Labels: adhoc, t-platform

#930 feat: Add LogisticalRegressionPredictor - rendering type predictor for adaptive crawling
  poetry.lock
  pyproject.toml
  src/crawlee/crawlers/_adaptive_playwright/__init__.py
  src/crawlee/crawlers/_adaptive_playwright/_rendering_type_predictor.py
  tests/unit/crawlers/_adaptive_playwright/test_predictor.py
Labels: enhancement, t-tooling, tested

#936 docs: update setting up and running in cloud
  Makefile
  README.md
  docs/deployment/apify_platform.mdx
  docs/guides/http_clients.mdx
  docs/guides/storages.mdx
  docs/introduction/01_setting_up.mdx
  docs/introduction/08_refactoring.mdx
  docs/introduction/09_running_in_cloud.mdx
  docs/quick-start/index.mdx
  pyproject.toml
  src/crawlee/project_template/{{cookiecutter.project_name}}/README.md
  website/docusaurus.config.js
  website/src/pages/index.js
Labels: documentation, t-tooling, adhoc

#948 ci: Do not wait for code checks on release if the head commit skips CI
  .github/workflows/release.yaml
Labels: t-tooling, adhoc
