Repository apify/crawlee-python, pull requests merged in 2025-03, with the labels that each got.

#1044 fix: Add `browserforge` to mandatory dependencies
  pyproject.toml
  uv.lock
Labels: bug, t-tooling, adhoc

#1045 chore: Always run checks in release workflow
  .github/workflows/release.yaml
Labels: t-tooling, adhoc

#1014 feat: Extend ErrorTracker with error grouping
  src/crawlee/statistics/_error_tracker.py
  tests/unit/_statistics/test_error_tracker.py
Labels: t-tooling, tested

#1049 fix: update project templates for Poetry v2.x compatibility
  src/crawlee/project_template/hooks/pre_gen_project.py
  src/crawlee/project_template/{{cookiecutter.project_name}}/Dockerfile
  src/crawlee/project_template/{{cookiecutter.project_name}}/_pyproject.toml
  uv.lock
Labels: t-tooling

#1060 feat: Use fingerprint generator in `PlaywrightCrawler` by default
  docs/guides/avoid_blocking.mdx
  docs/guides/code_examples/browser_fingerprint/playwright_with_fingerprint_generator.py
  src/crawlee/crawlers/_playwright/_playwright_crawler.py
  src/crawlee/fingerprint_suite/_browserforge_adapter.py
  tests/unit/crawlers/_playwright/test_playwright_crawler.py
Labels: t-tooling, tested

#1065 chore(deps): fix linting for new Ruff version
  src/crawlee/_types.py
  src/crawlee/statistics/_statistics.py
  uv.lock
Labels: t-tooling, adhoc

#1073 fix: Temporary workaround for `browserforge` import time code execution
  Makefile
  pyproject.toml
  src/crawlee/_browserforge_workaround.py
  src/crawlee/browsers/__init__.py
  src/crawlee/fingerprint_suite/__init__.py
  uv.lock
Labels: t-tooling, adhoc

#1075 fix: Update to `browserforge` workaround
  src/crawlee/_browserforge_workaround.py
  src/crawlee/fingerprint_suite/_browserforge_adapter.py
Labels: t-tooling, adhoc

#1083 chore: Add `sortedcontainers` to the project dependencies
  pyproject.toml
  uv.lock
Labels: t-tooling, adhoc

#1087 chore: update Ruff to v0.10
  pyproject.toml
  src/crawlee/_autoscaling/snapshotter.py
  src/crawlee/_cli.py
  src/crawlee/_request.py
  src/crawlee/_types.py
  src/crawlee/_utils/models.py
  src/crawlee/browsers/_playwright_browser_controller.py
  src/crawlee/crawlers/_basic/_basic_crawler.py
  src/crawlee/crawlers/_basic/_context_pipeline.py
  src/crawlee/events/_event_manager.py
  src/crawlee/http_clients/_httpx.py
  src/crawlee/statistics/_statistics.py
  src/crawlee/storages/_dataset.py
  tests/unit/_autoscaling/test_autoscaled_pool.py
  tests/unit/_autoscaling/test_snapshotter.py
  tests/unit/conftest.py
  tests/unit/crawlers/_adaptive_playwright/test_adaptive_playwright_crawler.py
  tests/unit/crawlers/_basic/test_basic_crawler.py
  tests/unit/storages/test_key_value_store.py
  uv.lock
Labels: t-tooling, adhoc, tested

#1094 chore: update to Ruff v0.11
  pyproject.toml
  src/crawlee/_browserforge_workaround.py
  src/crawlee/browsers/__init__.py
  src/crawlee/fingerprint_suite/__init__.py
  uv.lock
Labels: t-tooling, adhoc

#1095 chore(deps): rm unused dev deps
  pyproject.toml
  uv.lock
Labels: t-tooling, adhoc

#1061 feat: Add `statistics_log_format` parameter to `BasicCrawler`
  docs/examples/code_examples/configure_json_logging.py
  docs/examples/json_logging.mdx
  pyproject.toml
  src/crawlee/crawlers/_basic/_basic_crawler.py
  src/crawlee/statistics/_models.py
  src/crawlee/statistics/_statistics.py
  tests/unit/crawlers/_basic/test_basic_crawler.py
Labels: t-tooling

#1100 docs: Use and enforce imperative mood
  pyproject.toml
  src/crawlee/_autoscaling/autoscaled_pool.py
  src/crawlee/_autoscaling/snapshotter.py
  src/crawlee/_autoscaling/system_status.py
  src/crawlee/_log_config.py
  src/crawlee/_types.py
  src/crawlee/_utils/console.py
  src/crawlee/_utils/context.py
  src/crawlee/_utils/crypto.py
  src/crawlee/_utils/docs.py
  src/crawlee/_utils/file.py
  src/crawlee/_utils/recurring_task.py
  src/crawlee/_utils/requests.py
  src/crawlee/_utils/system.py
  src/crawlee/browsers/_browser_pool.py
  src/crawlee/browsers/_playwright_browser_controller.py
  src/crawlee/browsers/_playwright_browser_plugin.py
  src/crawlee/crawlers/_abstract_http/_abstract_http_crawler.py
  src/crawlee/crawlers/_abstract_http/_http_crawling_context.py
  src/crawlee/crawlers/_adaptive_playwright/_adaptive_playwright_crawler.py
  src/crawlee/crawlers/_adaptive_playwright/_adaptive_playwright_crawling_context.py
  src/crawlee/crawlers/_adaptive_playwright/_rendering_type_predictor.py
  src/crawlee/crawlers/_adaptive_playwright/_result_comparator.py
  src/crawlee/crawlers/_basic/_basic_crawler.py
  src/crawlee/crawlers/_beautifulsoup/_beautifulsoup_crawler.py
  src/crawlee/crawlers/_beautifulsoup/_beautifulsoup_crawling_context.py
  src/crawlee/crawlers/_beautifulsoup/_utils.py
  src/crawlee/crawlers/_http/_http_crawler.py
  src/crawlee/crawlers/_parsel/_parsel_crawler.py
  src/crawlee/crawlers/_parsel/_parsel_crawling_context.py
  src/crawlee/crawlers/_parsel/_utils.py
  src/crawlee/crawlers/_playwright/_playwright_crawler.py
  src/crawlee/events/_event_manager.py
  src/crawlee/events/_local_event_manager.py
  src/crawlee/fingerprint_suite/_browserforge_adapter.py
  src/crawlee/fingerprint_suite/_header_generator.py
  src/crawlee/http_clients/_base.py
  src/crawlee/http_clients/_curl_impersonate.py
  src/crawlee/http_clients/_httpx.py
  src/crawlee/proxy_configuration.py
  src/crawlee/request_loaders/_request_list.py
  src/crawlee/request_loaders/_request_loader.py
  src/crawlee/request_loaders/_request_manager.py
  src/crawlee/router.py
  src/crawlee/sessions/_session.py
  src/crawlee/sessions/_session_pool.py
  src/crawlee/statistics/_statistics.py
  src/crawlee/storage_clients/_base/_dataset_client.py
  src/crawlee/storage_clients/_base/_request_queue_client.py
  src/crawlee/storage_clients/_base/_storage_client.py
  src/crawlee/storage_clients/_memory/_creation_management.py
  src/crawlee/storage_clients/_memory/_dataset_client.py
  src/crawlee/storage_clients/_memory/_memory_storage_client.py
  src/crawlee/storage_clients/_memory/_request_queue_client.py
  src/crawlee/storages/_dataset.py
  src/crawlee/storages/_key_value_store.py
  src/crawlee/storages/_request_queue.py
  tests/unit/_utils/test_file.py
  tests/unit/crawlers/_adaptive_playwright/test_predictor.py
Labels: t-tooling, adhoc

#1092 chore: add uvicorn server for tests
  pyproject.toml
  tests/__init__.py
  tests/unit/__init__.py
  tests/unit/browsers/test_browser_pool.py
  tests/unit/browsers/test_playwright_browser_controller.py
  tests/unit/browsers/test_playwright_browser_plugin.py
  tests/unit/conftest.py
  tests/unit/crawlers/_basic/test_basic_crawler.py
  tests/unit/crawlers/_basic/test_context_pipeline.py
  tests/unit/crawlers/_http/test_http_crawler.py
  tests/unit/crawlers/_playwright/test_playwright_crawler.py
  tests/unit/http_clients/test_curl_impersonate.py
  tests/unit/http_clients/test_httpx.py
  tests/unit/server.py
  tests/unit/test_configuration.py
  uv.lock
Labels: t-tooling

#1114 fix: update favicon
  website/static/img/favicon.ico
Labels: adhoc, t-web
