Repository apify/crawlee-python, pull requests merged in 2025-04, with the labels that each got.

#1109 chore: Add templates Apify E2E tests
  .github/workflows/templates_e2e_tests.yaml
  CONTRIBUTING.md
  Makefile
  pyproject.toml
  src/crawlee/_cli.py
  src/crawlee/project_template/hooks/post_gen_project.py
  src/crawlee/project_template/{{cookiecutter.project_name}}/Dockerfile
  src/crawlee/project_template/{{cookiecutter.project_name}}/pyproject.toml
  tests/e2e/__init__.py
  tests/e2e/conftest.py
  tests/e2e/project_template/test_static_crawlers_templates.py
  tests/e2e/project_template/utils.py
  tests/integration/README.md
  uv.lock
Labels: t-tooling, debt, tested

#1024 feat: Add `requests` argument to `EnqueueLinksFunction`
  docs/examples/code_examples/extract_and_add_specific_links_on_website_bs.py
  docs/examples/code_examples/extract_and_add_specific_links_on_website_pw.py
  docs/examples/crawl_specific_links_on_website.mdx
  src/crawlee/_types.py
  src/crawlee/crawlers/_abstract_http/_abstract_http_crawler.py
  src/crawlee/crawlers/_abstract_http/_http_crawling_context.py
  src/crawlee/crawlers/_playwright/_playwright_crawler.py
  src/crawlee/crawlers/_playwright/_playwright_crawling_context.py
  tests/unit/crawlers/_parsel/test_parsel_crawler.py
  tests/unit/crawlers/_playwright/test_playwright_crawler.py
Labels: enhancement, t-tooling, tested

#1125 feat: Add `ErrorSnapshotter` to `ErrorTracker`
  docs/examples/capturing_page_snapshots_with_error_snapshotter.mdx
  docs/examples/code_examples/parsel_crawler_with_error_snapshotter.py
  docs/examples/code_examples/playwright_crawler_with_error_snapshotter.py
  docs/examples/crawl_specific_links_on_website.mdx
  pyproject.toml
  src/crawlee/_types.py
  src/crawlee/crawlers/_abstract_http/_http_crawling_context.py
  src/crawlee/crawlers/_basic/_basic_crawler.py
  src/crawlee/crawlers/_basic/_context_pipeline.py
  src/crawlee/crawlers/_playwright/_playwright_crawler.py
  src/crawlee/crawlers/_playwright/_playwright_pre_nav_crawling_context.py
  src/crawlee/statistics/_error_snapshotter.py
  src/crawlee/statistics/_error_tracker.py
  src/crawlee/statistics/_statistics.py
  tests/unit/_statistics/test_error_tracker.py
  tests/unit/crawlers/_http/test_http_crawler.py
  tests/unit/crawlers/_playwright/test_playwright_crawler.py
  tests/unit/server.py
  tests/unit/server_endpoints.py
Labels: enhancement, t-tooling, tested

#1140 fix: Improve validation errors in Crawlee CLI
  src/crawlee/_cli.py
  src/crawlee/project_template/hooks/pre_gen_project.py
Labels: t-tooling

#1156 fix: disable logger propagation to prevent duplicate logs
  src/crawlee/_log_config.py
Labels: bug, t-tooling, adhoc

#1155 fix: Update `UnprocessedRequest` to match actual data
  src/crawlee/storage_clients/models.py
  tests/unit/storage_clients/_memory/test_memory_storage_client.py
Labels: t-tooling, tested

#1159 feat: Handle unprocessed requests in `add_requests_batched`
  src/crawlee/storages/_request_queue.py
  tests/unit/storages/test_request_queue.py
Labels: t-tooling, tested

#1157 docs: small ui fixes and new og image
  website/docusaurus.config.js
  website/src/components/Homepage/LanguageInfoWidget.module.css
  website/src/theme/Navbar/Logo/index.module.css
  website/static/img/crawlee-og.png
  website/static/img/crawlee-python-og.png
Labels: t-web

#1177 chore: Update `test_enqueue_links` to use test server
  tests/unit/crawlers/_parsel/test_parsel_crawler.py
  tests/unit/crawlers/_playwright/test_playwright_crawler.py
Labels: t-tooling, adhoc, debt, tested

#1170 feat: Make timeout error log cleaner
  src/crawlee/crawlers/_basic/_basic_crawler.py
  src/crawlee/crawlers/_basic/_logging_utils.py
  tests/unit/crawlers/_basic/test_basic_crawler.py
Labels: enhancement, t-tooling, adhoc, tested

#1174 docs: Add guide for running crawler in web server
  docs/guides/code_examples/running_in_web_server/__init__.py
  docs/guides/code_examples/running_in_web_server/crawler.py
  docs/guides/code_examples/running_in_web_server/server.py
  docs/guides/running_in_web_server.mdx
  pyproject.toml
Labels: documentation, t-tooling

#1172 refactor: RecoverableState abstraction
  src/crawlee/_utils/recoverable_state.py
  src/crawlee/crawlers/_adaptive_playwright/_adaptive_playwright_crawler.py
  src/crawlee/fingerprint_suite/_types.py
  src/crawlee/sessions/_models.py
  src/crawlee/sessions/_session.py
  src/crawlee/sessions/_session_pool.py
  src/crawlee/statistics/__init__.py
  src/crawlee/statistics/_error_snapshotter.py
  src/crawlee/statistics/_error_tracker.py
  src/crawlee/statistics/_models.py
  src/crawlee/statistics/_statistics.py
  src/crawlee/storages/_creation_management.py
  src/crawlee/storages/_key_value_store.py
  tests/unit/crawlers/_adaptive_playwright/test_adaptive_playwright_crawler.py
  tests/unit/crawlers/_adaptive_playwright/test_adaptive_playwright_crawler_statistics.py
  tests/unit/crawlers/_playwright/test_playwright_crawler.py
  tests/unit/sessions/test_models.py
  tests/unit/sessions/test_session_pool.py
  tests/unit/storages/test_key_value_store.py
Labels: t-tooling, tested
