Repository apify/crawlee-python, pull requests merged in 2025-06, with the labels that each got.

#1237 chore: fix `PytestConfigWarning` by adding `pytest-timeout`
  pyproject.toml
  uv.lock
Labels: t-tooling, adhoc

#1236 chore: fix `PytestCollectionWarning` by adding `__test__=False`
  tests/unit/crawlers/_adaptive_playwright/test_adaptive_playwright_crawler.py
  tests/unit/storages/test_request_manager_tandem.py
Labels: t-tooling, adhoc, tested

#1239 chore: fix `UserWarning` `pkg_resources` is deprecated
  pyproject.toml
  uv.lock
Labels: t-tooling, adhoc

#1240 chore: fix `GuessedAtParserWarning` in BeautifulSoup
  src/crawlee/crawlers/_beautifulsoup/_utils.py
  tests/unit/_utils/test_html_to_text.py
Labels: t-tooling, adhoc, tested

#1245 chore: Fix incremental test coverage
  Makefile
Labels: t-tooling, adhoc

#1248 docs: fix build
  website/package.json
  website/yarn.lock
Labels: t-tooling, adhoc

#1260 fix: Use `perf_counter_ns` for request duration tracking
  src/crawlee/statistics/_statistics.py
  tests/unit/_statistics/test_request_processing_record.py
Labels: t-tooling, tested
