Repository apify/crawlee-python, pull requests merged in 2025-08, with the labels that each got.

#1357 refactor!: Change Dataset unwind parameter to accept list of strings
  src/crawlee/_types.py
  src/crawlee/storage_clients/_base/_dataset_client.py
  src/crawlee/storage_clients/_file_system/_dataset_client.py
  src/crawlee/storage_clients/_memory/_dataset_client.py
  src/crawlee/storages/_dataset.py
Labels: t-tooling, adhoc

#1362 chore: Remove sortedcollections and sortedcontainers packages
  pyproject.toml
  src/crawlee/_autoscaling/snapshotter.py
  tests/unit/_autoscaling/test_snapshotter.py
  uv.lock
Labels: t-tooling, tested

#1369 chore: Cleanup after 1.0.0rc1 release
  CHANGELOG.md
  pyproject.toml
  uv.lock
Labels: t-tooling, adhoc

#1374 docs: Update `RequestLoader.fetch_next_request` docblock
  src/crawlee/request_loaders/_request_loader.py
Labels: t-tooling, adhoc

#1376 docs: Update Request loaders guide
  docs/guides/code_examples/playwright_crawler_adaptive/handler.py
  docs/guides/code_examples/request_loaders/rl_basic_example.py
  docs/guides/code_examples/request_loaders/rl_tandem_example.py
  docs/guides/code_examples/request_loaders/rl_tandem_example_explicit.py
  docs/guides/code_examples/request_loaders/sitemap_basic_example.py
  docs/guides/code_examples/request_loaders/sitemap_example.py
  docs/guides/code_examples/request_loaders/sitemap_tandem_example.py
  docs/guides/code_examples/request_loaders/sitemap_tandem_example_explicit.py
  docs/guides/request_loaders.mdx
  docs/guides/service_locator.mdx
  pyproject.toml
  src/crawlee/fingerprint_suite/_fingerprint_generator.py
Labels: documentation, t-tooling, adhoc
