Repository apify/crawlee-python, pull requests merged in 2025-07, with the labels that each got.

#1281 chore: Bump minimum Python version to 3.10
  .github/workflows/run_code_checks.yaml
  CONTRIBUTING.md
  docs/guides/code_examples/session_management/multi_sessions_http.py
  docs/introduction/01_setting_up.mdx
  docs/quick-start/index.mdx
  pyproject.toml
  src/crawlee/_autoscaling/_types.py
  src/crawlee/_autoscaling/autoscaled_pool.py
  src/crawlee/_types.py
  src/crawlee/_utils/context.py
  src/crawlee/_utils/docs.py
  src/crawlee/_utils/models.py
  src/crawlee/_utils/recurring_task.py
  src/crawlee/crawlers/_abstract_http/_abstract_http_crawler.py
  src/crawlee/crawlers/_basic/_basic_crawler.py
  src/crawlee/crawlers/_basic/_context_pipeline.py
  src/crawlee/crawlers/_playwright/_playwright_crawler.py
  src/crawlee/crawlers/_playwright/_playwright_crawling_context.py
  src/crawlee/events/_event_manager.py
  src/crawlee/events/_types.py
  src/crawlee/fingerprint_suite/_browserforge_adapter.py
  src/crawlee/http_clients/_curl_impersonate.py
  src/crawlee/http_clients/_httpx.py
  src/crawlee/project_template/{{cookiecutter.project_name}}/pyproject.toml
  src/crawlee/proxy_configuration.py
  src/crawlee/router.py
  src/crawlee/sessions/_session_pool.py
  src/crawlee/statistics/_error_tracker.py
  src/crawlee/statistics/_models.py
  src/crawlee/storages/_storage_instance_manager.py
  tests/unit/_utils/test_html_to_text.py
  tests/unit/_utils/test_system.py
  tests/unit/conftest.py
  tests/unit/crawlers/_http/test_http_crawler.py
  tests/unit/server.py
  uv.lock
Labels: t-tooling, tested

#1284 chore: update development status from beta to stable
  pyproject.toml
Labels: t-tooling, adhoc

#1285 chore: use well known labels for project.urls
  pyproject.toml
Labels: t-tooling, adhoc

#1273 docs: Add guide about creating and using WARC files with `Crawlee`
  docs/guides/code_examples/creating_web_archive/manual_archiving_parsel_crawler.py
  docs/guides/code_examples/creating_web_archive/manual_archiving_playwright_crawler.py
  docs/guides/code_examples/creating_web_archive/simple_pw_through_proxy_pywb_server.py
  docs/guides/creating_web_archive.mdx
  pyproject.toml
Labels: documentation, t-tooling

#1294 feat: Add crawlee-cli option to skip project installation
  src/crawlee/_cli.py
  src/crawlee/project_template/cookiecutter.json
  src/crawlee/project_template/hooks/post_gen_project.py
  tests/e2e/project_template/test_static_crawlers_templates.py
  tests/unit/test_cli.py
Labels: enhancement, t-tooling, tested

#1255 feat: Add basic `OpenTelemetry` instrumentation
  docs/guides/code_examples/trace_and_monitor_crawlers/instrument_crawler.py
  docs/guides/trace_and_monitor_crawlers.mdx
  pyproject.toml
  src/crawlee/crawlers/_basic/_context_pipeline.py
  src/crawlee/otel/__init__.py
  src/crawlee/otel/crawler_instrumentor.py
  tests/unit/otel/test_crawler_instrumentor.py
  uv.lock
  website/static/img/guides/jaeger_otel_search_view_example.png
  website/static/img/guides/jaeger_otel_trace_example.png
Labels: enhancement, t-tooling, tested

#1303 chore: Re-use optional dependencies for `all`
  pyproject.toml
  uv.lock
Labels: t-tooling

#1299 chore: Refactor `HttpClient` implementations tests
  tests/unit/http_clients/test_http_clients.py
  tests/unit/http_clients/test_httpx.py
  tests/unit/http_clients/test_impit.py
Labels: t-tooling, debt, tested

#1270 feat: Prevent overloading system memory when running locally
  src/crawlee/_autoscaling/_types.py
  src/crawlee/_autoscaling/snapshotter.py
  src/crawlee/_utils/system.py
  tests/unit/_autoscaling/test_snapshotter.py
  tests/unit/_autoscaling/test_system_status.py
  uv.lock
Labels: t-tooling, tested

#1306 docs: Add architecture overview guide and more
  docs/examples/code_examples/adaptive_playwright_crawler.py
  docs/examples/playwright_crawler_adaptive.mdx
  docs/guides/architecture_overview.mdx
  docs/guides/code_examples/error_handling/change_handle_error_status.py
  docs/guides/code_examples/http_clients/parsel_curl_impersonate_example.py
  docs/guides/code_examples/http_clients/parsel_httpx_example.py
  docs/guides/code_examples/http_clients/parsel_impit_example.py
  docs/guides/code_examples/http_crawlers/beautifulsoup_example.py
  docs/guides/code_examples/http_crawlers/custom_crawler_example.py
  docs/guides/code_examples/http_crawlers/http_example.py
  docs/guides/code_examples/http_crawlers/parsel_example.py
  docs/guides/code_examples/request_loaders/rl_tandem_example.py
  docs/guides/code_examples/request_loaders/rl_tandem_example_explicit.py
  docs/guides/code_examples/request_loaders/sitemap_tandem_example.py
  docs/guides/code_examples/request_loaders/sitemap_tandem_example_explicit.py
  docs/guides/code_examples/request_router/adaptive_crawler_handlers.py
  docs/guides/code_examples/request_router/basic_request_handlers.py
  docs/guides/code_examples/request_router/custom_router_default_only.py
  docs/guides/code_examples/request_router/error_handler.py
  docs/guides/code_examples/request_router/failed_request_handler.py
  docs/guides/code_examples/request_router/http_pre_navigation.py
  docs/guides/code_examples/request_router/playwright_pre_navigation.py
  docs/guides/code_examples/request_router/simple_default_handler.py
  docs/guides/code_examples/service_locator/service_conflicts.py
  docs/guides/code_examples/service_locator/service_crawler_configuration.py
  docs/guides/code_examples/service_locator/service_crawler_event_manager.py
  docs/guides/code_examples/service_locator/service_crawler_storage_client.py
  docs/guides/code_examples/service_locator/service_locator_configuration.py
  docs/guides/code_examples/service_locator/service_locator_event_manager.py
  docs/guides/code_examples/service_locator/service_locator_storage_client.py
  docs/guides/code_examples/service_locator/service_storage_configuration.py
  docs/guides/code_examples/service_locator/service_storage_storage_client.py
  docs/guides/code_examples/storage_clients/registering_storage_clients_example.py
  docs/guides/http_clients.mdx
  docs/guides/http_crawlers.mdx
  docs/guides/playwright_crawler.mdx
  docs/guides/playwright_crawler_adaptive.mdx
  docs/guides/request_loaders.mdx
  docs/guides/request_router.mdx
  docs/guides/service_locator.mdx
  docs/guides/storage_clients.mdx
  docs/guides/storages.mdx
  docs/introduction/03_adding_more_urls.mdx
  src/crawlee/crawlers/_adaptive_playwright/_adaptive_playwright_crawler.py
  website/sidebars.js
  website/src/pages/home_page_example.py
Labels: t-tooling

#1319 docs: switch from pipx to uvx
  README.md
  docs/introduction/01_setting_up.mdx
  docs/introduction/09_running_in_cloud.mdx
  docs/upgrading/upgrading_to_v1.md
  website/src/components/Homepage/HomepageCliExample.jsx
Labels: t-tooling, adhoc

#1330 fix: Fix memory estimation not working on MacOS
  src/crawlee/_utils/system.py
  tests/unit/_utils/test_system.py
Labels: bug, t-tooling, tested

#1328 fix: Fix retry count to not count the original request
  src/crawlee/crawlers/_basic/_basic_crawler.py
  tests/unit/crawlers/_basic/test_basic_crawler.py
  tests/unit/crawlers/_http/test_http_crawler.py
  tests/unit/crawlers/_playwright/test_playwright_crawler.py
Labels: bug, t-tooling, tested

#1337 docs: Port changelog updates from maintenance branch
  CHANGELOG.md
  pyproject.toml
Labels: t-tooling, adhoc
