Repository apify/crawlee-python, pull requests merged in 2025-09, with the labels that each got.

#1389 chore: Update Impit to v0.6.1
  pyproject.toml
  uv.lock
Labels: t-tooling, adhoc

#1425 refactor: Give more instance caching flexibility to the storage clients
  src/crawlee/storage_clients/_base/_storage_client.py
  src/crawlee/storage_clients/_file_system/_storage_client.py
  src/crawlee/storages/_dataset.py
  src/crawlee/storages/_key_value_store.py
  src/crawlee/storages/_request_queue.py
  src/crawlee/storages/_storage_instance_manager.py
Labels: t-tooling

#1419 fix: Set default desired concurrency for non-browser crawlers to 10
  src/crawlee/_types.py
  src/crawlee/crawlers/_adaptive_playwright/_adaptive_playwright_crawler.py
  src/crawlee/crawlers/_playwright/_playwright_crawler.py
  tests/unit/_autoscaling/test_autoscaled_pool.py
  tests/unit/crawlers/_basic/test_basic_crawler.py
  tests/unit/crawlers/_beautifulsoup/test_beautifulsoup_crawler.py
  tests/unit/crawlers/_http/test_http_crawler.py
  tests/unit/crawlers/_parsel/test_parsel_crawler.py
  tests/unit/crawlers/_playwright/test_playwright_crawler.py
Labels: t-tooling, adhoc, tested

#1432 chore: Prevent request manager change after crawler restart
  src/crawlee/crawlers/_basic/_basic_crawler.py
  tests/unit/crawlers/_basic/test_basic_crawler.py
Labels: t-tooling, adhoc, tested

#1433 docs: Remove outdated note about early adopters
  README.md
Labels: t-tooling, adhoc
