Repository apify/crawlee-python, pull requests merged in 2025-02, with the labels that each got.

#952 fix: Fix templates - poetry-plugin-export version and camoufox template name
  src/crawlee/project_template/{{cookiecutter.project_name}}/Dockerfile
  src/crawlee/project_template/{{cookiecutter.project_name}}/_pyproject.toml
  src/crawlee/project_template/{{cookiecutter.project_name}}/requirements.txt
Labels: bug, t-tooling

#829 feat: Integrate browserforge fingerprints
  Makefile
  docs/examples/code/playwright_crawler_with_fingerprint_generator.py
  docs/examples/playwright_crawler_with_fingerprint_generator.mdx
  poetry.lock
  pyproject.toml
  src/crawlee/browsers/_browser_pool.py
  src/crawlee/browsers/_playwright_browser_controller.py
  src/crawlee/browsers/_playwright_browser_plugin.py
  src/crawlee/crawlers/_playwright/_playwright_crawler.py
  src/crawlee/fingerprint_suite/__init__.py
  src/crawlee/fingerprint_suite/_browserforge_adapter.py
  src/crawlee/fingerprint_suite/_fingerprint_generator.py
  src/crawlee/fingerprint_suite/_header_generator.py
  src/crawlee/fingerprint_suite/_types.py
  tests/unit/crawlers/_playwright/test_playwright_crawler.py
  tests/unit/fingerprint_suite/test_adapters.py
Labels: enhancement, t-tooling, tested

#872 feat: Add AdaptivePlaywrightCrawler
  docs/examples/code/adaptive_playwright_crawler.py
  src/crawlee/_types.py
  src/crawlee/crawlers/__init__.py
  src/crawlee/crawlers/_abstract_http/_abstract_http_crawler.py
  src/crawlee/crawlers/_adaptive_playwright/__init__.py
  src/crawlee/crawlers/_adaptive_playwright/_adaptive_playwright_crawler.py
  src/crawlee/crawlers/_adaptive_playwright/_adaptive_playwright_crawler_statistics.py
  src/crawlee/crawlers/_adaptive_playwright/_adaptive_playwright_crawling_context.py
  src/crawlee/crawlers/_adaptive_playwright/_rendering_type_predictor.py
  src/crawlee/crawlers/_adaptive_playwright/_result_comparator.py
  src/crawlee/crawlers/_basic/_basic_crawler.py
  src/crawlee/crawlers/_playwright/_playwright_crawler.py
  src/crawlee/crawlers/_playwright/_playwright_pre_nav_crawling_context.py
  src/crawlee/statistics/_statistics.py
  tests/unit/_statistics/test_periodic_logging.py
  tests/unit/_statistics/test_persistence.py
  tests/unit/crawlers/_adaptive_playwright/test_adaptive_playwright_crawler.py
  tests/unit/crawlers/_adaptive_playwright/test_adaptive_playwright_crawler_statistics.py
  tests/unit/http_clients/test_curl_impersonate.py
  tests/unit/http_clients/test_httpx.py
Labels: t-tooling, tested

#965 chore: switch to the common self-hosted HTTPBin instance
  .github/workflows/run_code_checks.yaml
Labels: t-tooling, adhoc

#972 fix: Fix playwright template and dockerfile
  src/crawlee/project_template/templates/routes_playwright.py
  src/crawlee/project_template/{{cookiecutter.project_name}}/Dockerfile
  src/crawlee/project_template/{{cookiecutter.project_name}}/{{cookiecutter.__package_name}}/__main__.py
Labels: t-tooling

#973 docs: Set line length to docs related code to 90
  docs/examples/code/adaptive_playwright_crawler.py
  docs/examples/code/beautifulsoup_crawler.py
  docs/examples/code/beautifulsoup_crawler_keep_alive.py
  docs/examples/code/beautifulsoup_crawler_stop.py
  docs/examples/code/crawl_website_with_relative_links_all_links.py
  docs/examples/code/playwright_block_requests.py
  docs/examples/code/playwright_crawler.py
  docs/examples/code/playwright_crawler_with_camoufox.py
  docs/examples/code/playwright_crawler_with_fingerprint_generator.py
  docs/guides/code/playwright_crawler/browser_configuration_example.py
  docs/guides/code/playwright_crawler/multiple_launch_example.py
  docs/guides/code/playwright_crawler/pre_navigation_hook_example.py
  docs/guides/code/proxy_management/tiers_bs_example.py
  docs/guides/code/proxy_management/tiers_pw_example.py
  docs/guides/code/storages/rq_basic_example.py
  docs/guides/code/storages/rq_with_crawler_example.py
  docs/guides/code/storages/rq_with_crawler_explicit_example.py
  docs/introduction/code/03_transform_request.py
  docs/introduction/code/04_sanity_check.py
  docs/introduction/code/06_scraping.py
  docs/introduction/code/07_final_code.py
  docs/pyproject.toml
  docs/quick-start/code/beautifulsoup_crawler_example.py
  docs/quick-start/code/parsel_crawler_example.py
  docs/quick-start/code/playwright_crawler_example.py
Labels: documentation, t-tooling

#974 chore: Fix flakiness in test and use explicit test id
  tests/unit/_utils/test_html_to_text.py
  tests/unit/crawlers/_basic/test_basic_crawler.py
Labels: t-tooling, adhoc, debt, tested

#977 fix: Fix installing dependencies via pip in project template
  src/crawlee/project_template/{{cookiecutter.project_name}}/Dockerfile
Labels: t-tooling

#961 docs: Add anti-blocking guide
  docs/guides/avoid_blocking.mdx
  docs/guides/code/browser_fingerprint/default_fingerprint_generator_with_args.py
  docs/guides/code/browser_fingerprint/playwright_with_fingerprint_generator.py
Labels: documentation, t-tooling

#978 refactor!: remove unused config properties
  docs/upgrading/upgrading_to_v0x.md
  src/crawlee/_log_config.py
  src/crawlee/configuration.py
Labels: t-tooling

#979 ci: Trigger docs build even after docs commits
  .github/workflows/pre_release.yaml
Labels: t-tooling, adhoc

#982 chore: rm Apify as optional dependecy
  docs/deployment/apify_platform.mdx
  poetry.lock
  pyproject.toml
Labels: t-tooling, adhoc

#964 feat: Add adaptive context helpers
  docs/examples/code/adaptive_playwright_crawler.py
  docs/examples/playwright_crawler_adaptive.mdx
  docs/guides/code/adaptive_playwright_crawler/adaptive_playwright_crawler_handler.py
  docs/guides/code/adaptive_playwright_crawler/adaptive_playwright_crawler_init_beautifulsoup.py
  docs/guides/code/adaptive_playwright_crawler/adaptive_playwright_crawler_init_parsel.py
  docs/guides/code/adaptive_playwright_crawler/adaptive_playwright_crawler_init_prediction.py
  docs/guides/code/adaptive_playwright_crawler/adaptive_playwright_crawler_pre_nav_hooks.py
  docs/guides/playwright_crawler_adaptive.mdx
  src/crawlee/crawlers/_abstract_http/_abstract_http_crawler.py
  src/crawlee/crawlers/_abstract_http/_abstract_http_parser.py
  src/crawlee/crawlers/_abstract_http/_http_crawling_context.py
  src/crawlee/crawlers/_adaptive_playwright/_adaptive_playwright_crawler.py
  src/crawlee/crawlers/_adaptive_playwright/_adaptive_playwright_crawling_context.py
  src/crawlee/crawlers/_beautifulsoup/_beautifulsoup_crawler.py
  src/crawlee/crawlers/_beautifulsoup/_beautifulsoup_parser.py
  src/crawlee/crawlers/_beautifulsoup/_utils.py
  src/crawlee/crawlers/_http/_http_crawler.py
  src/crawlee/crawlers/_http/_http_parser.py
  src/crawlee/crawlers/_parsel/_parsel_crawler.py
  src/crawlee/crawlers/_parsel/_parsel_parser.py
  tests/unit/crawlers/_adaptive_playwright/test_adaptive_playwright_crawler.py
  tests/unit/crawlers/_adaptive_playwright/test_adaptive_playwright_crawling_context.py
Labels: t-tooling, tested

#994 chore: migrate to uv package manager
  .github/workflows/build_and_deploy_docs.yaml
  .github/workflows/pre_release.yaml
  .github/workflows/release.yaml
  .github/workflows/run_code_checks.yaml
  .gitignore
  CONTRIBUTING.md
  Makefile
  poetry.lock
  pyproject.toml
  uv.lock
Labels: t-tooling

#996 chore: fix uv setup
  .github/workflows/build_and_deploy_docs.yaml
  CONTRIBUTING.md
  pyproject.toml
  uv.lock
Labels: t-tooling

#997 ci: switch apify workflow branch back to main
  .github/workflows/build_and_deploy_docs.yaml
  .github/workflows/pre_release.yaml
  .github/workflows/release.yaml
  .github/workflows/run_code_checks.yaml
Labels: t-tooling

#959 feat!: Enable additional status codes arguments to PlaywrightCrawler
  docs/guides/code/adaptive_playwright_crawler/adaptive_playwright_crawler_init_beautifulsoup.py
  docs/guides/code/adaptive_playwright_crawler/adaptive_playwright_crawler_init_parsel.py
  docs/upgrading/upgrading_to_v0x.md
  src/crawlee/crawlers/__init__.py
  src/crawlee/crawlers/_abstract_http/__init__.py
  src/crawlee/crawlers/_abstract_http/_abstract_http_crawler.py
  src/crawlee/crawlers/_adaptive_playwright/_adaptive_playwright_crawler.py
  src/crawlee/crawlers/_basic/_basic_crawler.py
  src/crawlee/crawlers/_beautifulsoup/_beautifulsoup_crawler.py
  src/crawlee/crawlers/_http/_http_crawler.py
  src/crawlee/crawlers/_parsel/_parsel_crawler.py
  tests/unit/crawlers/_http/test_http_crawler.py
  tests/unit/crawlers/_playwright/test_playwright_crawler.py
Labels: enhancement, t-tooling, tested

#1018 fix: Fix default migration storage
  src/crawlee/sessions/_models.py
  src/crawlee/sessions/_session_pool.py
  src/crawlee/statistics/_statistics.py
  tests/unit/sessions/test_session_pool.py
Labels: t-tooling, tested

#1023 fix: Fix logger name for http based loggers
  src/crawlee/crawlers/_abstract_http/_abstract_http_crawler.py
  tests/unit/crawlers/_beautifulsoup/test_beautifulsoup_crawler.py
  tests/unit/crawlers/_http/test_http_crawler.py
  tests/unit/crawlers/_parsel/test_parsel_crawler.py
Labels: bug, t-tooling, tested

#1025 docs: bump `typedoc-plugin`, use `@docusaurus/faster`
  website/docusaurus.config.js
  website/package.json
  website/yarn.lock
Labels: t-tooling, adhoc

#1030 fix: Fix flaky test_common_headers_and_user_agent
  tests/unit/fingerprint_suite/test_header_generator.py
  tests/unit/http_clients/test_httpx.py
Labels: bug, t-tooling, tested
